- client/Targets/DesignSystem/DesignKit/Sources/Buttons/ActionButton.swift
* #16 
* DefaultButton 추가
* AlertButton 추가
> 버튼 디자인 시스템 추가

- client/Targets/App/Sources/AppComponent.swift
- client/Targets/App/Sources/AppDelegate.swift
- client/Targets/App/Sources/AppRoot/AppRootBuilder.swift
- client/Targets/App/Sources/AppRoot/AppRootInteractor.swift
- client/Targets/App/Sources/AppRoot/AppRootRouter.swift
- client/Targets/App/Sources/AppRoot/AppRootTabBarController.swift
> AppRoot 리블렛 추가

- server/package-lock.json
- server/package.json
- server/src/app.module.ts
- server/src/auth/auth.controller.ts
- server/src/auth/auth.module.ts
- server/src/auth/auth.service.ts
- server/src/auth/dto/auth.credential.dto.ts
- server/src/auth/dto/auth.resgister.dto.ts
- server/src/db/database.providers.ts
- server/src/entities/user.entity.ts
- server/src/exception/http-exception.filter.ts
- server/src/user/user.providers.ts
- server/src/user/user.repository.ts
* #11 
- 로그인 기능 구현
- 이미 가입된 계정으로 로그인 시도 시, 새로 발급한 access 토큰 발급
- 가입되지 않은 계정인 경우 빈 access 토큰을 리턴
- 회원 가입 기능 구현
-  회원가입 성공 시 새로 발급한 access 토큰을 리턴
Naver 로그인 API를 활용하여 Access 토큰을 발급받으면, 해당 토큰과 postman을 이용하여 테스트할 수 있습니다.
OAuth AccessToken을 이용하여 로그인 성공 시, 아래와 같이 새로 발급한 Access Token을 Response로 응답합니다.
> 로그인/회원가입 기능 구현

- server/package-lock.json
- server/package.json
- server/src/auth/auth.controller.ts
- server/src/auth/dto/auth.credential.dto.ts
- server/src/auth/dto/auth.resgister.dto.ts
- server/src/main.ts
* #22  
- NestJS Swagger 설치
- signin, signup에 swagger 적용
- npm run start:dev 이후 'localhost:3000/api'로 이동하면 swagger 명세를 확인할 수 있습니다.
> NestJS Swagger 적용

- README.md
> README Figma 링크 수정

- client/Targets/Core/Network/NetworkAPIKit/Sources/Extensions/Encodable+Data.swift
- client/Targets/Core/Network/NetworkAPIKit/Sources/Extensions/String+Data.swift
- client/Targets/Core/Network/NetworkAPIKit/Sources/Extensions/URLRequest+NetworkHeader.swift
- client/Targets/Core/Network/NetworkAPIKit/Sources/HTTPMethod.swift
- client/Targets/Core/Network/NetworkAPIKit/Sources/MultipartFormData.swift
- client/Targets/Core/Network/NetworkAPIKit/Sources/Network.swift
- client/Targets/Core/Network/NetworkAPIKit/Sources/NetworkAPIKit.swift
- client/Targets/Core/Network/NetworkAPIKit/Sources/NetworkError.swift
- client/Targets/Core/Network/NetworkAPIKit/Sources/NetworkHeader.swift
- client/Targets/Core/Network/NetworkAPIKit/Sources/NetworkProvider.swift
- client/Targets/Core/Network/NetworkAPIKit/Sources/Target.swift
- client/Targets/Core/Network/NetworkAPIKit/Sources/Task.swift
- close #21
- 다음주부터 빠르게 작업을 하기 위해 네트워크 작업 먼저 진행했습니다.
- 이미지 업로드를 위한 MultipartFormData 추가했습니다.
- 저번에 구두로 date 인코딩을 iso8601라고 해서 설정해뒀습니다.
- Network 추가
- [MultipartFormData](https://lena-chamna.netlify.app/post/http_multipart_form-data/)
- [MultipartFormData-iOS](https://ios-development.tistory.com/1419)
> Network 추가

- client/Targets/DesignSystem/DesignKit/Sources/TextFields/SearchTextField.swift
* close #30 
* LeftView에 inset을 주기 위해 ContainerView를 생성하고 오토레이아웃 설정함
* 기존에 상수 값을 관리하는 Constants에 들어가는 것이 애매해서 class 내부에 private enum으로 상수값을 정의하여 사용함
* SearchTextField 추가
https://github.com/boostcampwm2023/iOS04-HeatPick/assets/74225754/b222176f-4603-4aea-bc6a-0f81709b2c2a
> SearchTextField 추가

- client/Plugins/UtilityPlugin/ProjectDescriptionHelpers/Dependency+Presentation.swift
- client/Plugins/UtilityPlugin/ProjectDescriptionHelpers/Dependency+Project.swift
- client/Plugins/UtilityPlugin/ProjectDescriptionHelpers/Scheme+.swift
- client/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
- client/Tuist/Stencils/AppDelegate.stencil
- client/Tuist/Stencils/AppIcon.stencil
- client/Tuist/Stencils/Assets_contents.stencil
- client/Tuist/Stencils/Info.stencil
- client/Tuist/Stencils/LaunchScreen.stencil
- client/Tuist/Stencils/Project-app
- client/Tuist/Stencils/Project-demo.stencil
- client/Tuist/Stencils/Project-implementations.stencil
- client/Tuist/Stencils/Project-interfaces.stencil
- client/Tuist/Templates/feature/feature.swift
* close #40 
* Presentation 템플릿 추가
* 첨부된 스크린샷을 통해 테스트할 수 있음
* [tuist scaffold](https://docs.tuist.io/commands/scaffold/)
> Feature 템플릿 추가

- .github/workflows/test-actions.yml
- package-lock.json
- server/.dockerignore
- server/Dockerfile
- server/src/db/dbConnection.ts
* #47 
- server branch push 시 자동 배포 스크립트가 동작하도록 구현하였습니다.
- docker image 생성 후, docker repository에 image를 업로드 합니다. 이후 서버로 ssh 연결을 수행한 후, docker image를 pull하여 가져온 후 실행시킵니다.
- 
- server branch에 push 시 자동으로 github action이 동작하여 스크립트를 수행합니다.
- 223.130.134.254:3000으로 API 요청을 보내 서버 동작 여부를 확인할 수 있습니다.
원격 서버에서 정상적으로 API가 동작하는 것을 확인할 수 있습니다.
> CI/CD 배포 환경 설정

- client/Targets/App/Sources/AppRoot/AppRootBuilder.swift
- client/Targets/App/Sources/AppRoot/AppRootRouter.swift
- client/Targets/App/Sources/AppRoot/AppRootTabBarController.swift
- client/Targets/Presentation/Search/Implementations/Sources/Search.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchHome/SearchHomeBuilder.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchHome/SearchHomeInteractor.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchHome/SearchHomeRouter.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchHome/SearchHomeViewController.swift
-  #50 
- Search 탭 추가 및 네이버 지도 뷰 추가
- Search 탭 어태취 ~
- AppRoot Router Dependency로 수정
- TabViewController TintColor hpBlackd으로 수정
> AppRoot 수정 및 Search Tab 어태취 ~

- .github/workflows/test-actions.yml
#67 
* PR이 develop 브랜치에 대해 merge && 서버 라벨이 달려있는 경우만 CI/CD 되도록 구현
> git workflow 동작 조건 변경

- server/src/entities/category.entity.ts
- server/src/entities/story.entity.ts
- server/src/entities/user.entity.ts
#69 
* Story Entity 생성
* Category Entity 생성
>  Story 및 Category Entity 생성

- server/src/entities/category.entity.ts
- server/src/entities/story.entity.ts
#83 
* import 에러 수정 typeorm/browser => typeorm
* Story, Category 잘못된 연관관계 수정
> import 에러 수정 및 Story, Category 잘못된 연관관계 수정

- client/Targets/App/Info.plist
- client/Targets/App/Sources/AppRoot/AppRootComponent.swift
- client/Targets/Core/Network/NetworkAPIAuth/Sources/SignUpTarget.swift
- client/Targets/Core/Network/NetworkAPIAuth/Sources/URLProtocols/AuthURLProtocol.swift
- client/Targets/Core/Network/NetworkAPIKit/Sources/NetworkError.swift
- client/Targets/Data/Network/Sources/Auth/SignUpRequestDTO.swift
- client/Targets/Data/Network/Sources/Auth/SignUpResponseDTO.swift
- client/Targets/Data/Repositories/Sources/AuthRepository.swift
- client/Targets/Data/Repositories/Sources/NaverLoginRepository.swift
- client/Targets/Domain/Interfaces/Sources/Repository/AuthRepositoryInterface.swift
- client/Targets/Domain/Interfaces/Sources/UseCase/AuthUseCaseInterface.swift
- client/Targets/Domain/UseCases/Sources/AuthUseCase.swift
- client/Targets/Presentation/Auth/Implementations/Sources/SignUp/SignUpBuilder.swift
- client/Targets/Presentation/Auth/Implementations/Sources/SignUp/SignUpInteractor.swift
- client/Targets/Presentation/Auth/Implementations/Sources/SignUp/SignUpViewController.swift
* close #35 
* 서버 통신 없이 URLProtocol로 하도록 설정해뒀습니다.
* 이슈에 있는 기능 (중복 체크, 서버 통신) 은 다른 이슈로 생성해서 빼두겠습니다
* 현재 서버가 http 지원을 해서 info 값 변경해뒀습니다 (추후 수정 예정)
* SignUp 서비스 추가
* SignUp Presentation 로직 수정
> 회원가입 서비스 추가

- server/.prettierrc
- server/package-lock.json
- server/package.json
- server/src/app.module.ts
- server/src/entities/category.entity.ts
- server/src/entities/story.entity.ts
- server/src/story/dto/story.create.dto.ts
- server/src/story/story.controller.ts
- server/src/story/story.module.ts
- server/src/story/story.providers.ts
- server/src/story/story.repository.ts
- server/src/story/story.service.ts
- server/src/story/util/story.util.saveImage.ts
#82 
* Story 생성에 대한 API 추가
* DateFormat은 미완성
> Story 생성 API 구현

- client/Targets/App/Sources/AppRoot/AppRootComponent.swift
- client/Targets/App/Sources/AppRoot/AppRootRouter.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryEditor/StoryEditorBuilder.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryEditor/StoryEditorInteractor.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryEditor/StoryEditorRouter.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryEditor/StoryEditorViewController.swift
* #53 
* 스토리 에디터 리블렛 추가
* 새 스토리 탭바 추가
* 퇴근 시간이 얼마 안남아 기본 설정한 부분까지 PR 날립니다 :)
> Story Editor 리블렛 추가, Tabbar 연결

- server/src/entities/profile-image.entity.ts
- server/src/entities/story-image.entity.ts
- server/src/story/story.controller.ts
#98 
- image 파일을 따로 관리하기 위해 profile image, story image entity를 정의하였습니다.
> profile image, story image entity 정의

- server/src/story/story.controller.ts
- server/src/story/story.repository.ts
- server/src/story/story.service.ts
- server/src/story/type/story.detail.view.data.ts
- server/src/story/type/story.user.data.ts
closed #103 
* Story 상세 API 구현
> Story 상세 API 구현

- server/package-lock.json
- server/package.json
- server/src/app.module.ts
- server/src/auth/auth.controller.ts
- server/src/auth/auth.service.ts
- server/src/exception/cuntom.exception/id.duplicate.exception.ts
- server/src/exception/custom-exception.filter.ts
- server/src/exception/http-exception.filter.ts
- server/src/main.ts
close #102 
- Exception filter 적용
- HTTP 요청 로그 기능 구현
- signin, signup 리턴 데이터 형식 변경(JSON 형태 string)
위와 같이, 요청 path와 status code를 확인할 수 있습니다.
> Exception filter 적용 및 로그 설정

- client/Targets/Presentation/Home/Implementations/Sources/Home/HomeInteractor.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/HomeViewController.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/HotPlaceDashboard/HomeHotPlaceDashboardViewController.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/RecommendDashboard/HomeRecommendDashboardInteractor.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/RecommendDashboard/HomeRecommendDashboardViewController.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/RecommendDashboard/Views/HomeRecommendContentView.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/Views/HomeTitleView.swift
* #62 
* Mock 데이터로 요청했습니다 (cc. https://picsum.photos/)
* 추천 장소 UI 추가
https://github.com/boostcampwm2023/iOS04-HeatPick/assets/74225754/659eadfe-17d8-488c-9d9a-493f38b0b6eb
> Home Recommend UI 추가

- client/Targets/Presentation/Home/Implementations/Sources/Home/HomeInteractor.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/HotPlaceDashboard/HomeHotPlaceDashboardInteractor.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/HotPlaceDashboard/HomeHotPlaceDashboardViewController.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/HotPlaceDashboard/Views/HomeHotPlaceContentView.swift
* #62 
* Mock 데이터로 요청했습니다 (cc. https://picsum.photos/)
* 핫플레이스 UI 추가
https://github.com/boostcampwm2023/iOS04-HeatPick/assets/74225754/acbc51c7-e701-4f56-934d-d82650092878
> HomeHotPlace UI 추가

- client/Targets/Core/CoreKit/Sources/Log/Log.swift
* close #86 
* Log에 있는 internal부분을 public 으로 변경
* Debug 모드에만 로그 찍도록 수정
> Log access level 수정, Debug 분기 추가

- client/.gitignore
- client/Plugins/UtilityPlugin/ProjectDescriptionHelpers/XCConfig.swift
- client/Targets/App/Info.plist
- client/Targets/Core/CoreKit/Sources/SecretUtil/Secret.swift
- client/Targets/Core/Network/NetworkAPIKit/Sources/NetworkHost.swift
- client/Targets/Data/Repositories/Sources/NaverLoginRepository.swift
- client/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
* close #45 
* XCConfig를 이용하여 Key 관리하도록 했습니다.
* DM으로 Key 파일 보내겠습니다!
* Secret Key 추가
> Secret Key 추가

- client/Targets/Presentation/Home/Implementations/Sources/Home/FollowingDashboard/HomeFollowingDashboardInteractor.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/FollowingDashboard/HomeFollowingDashboardViewController.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/FollowingDashboard/Views/HomeFollowingCommentView.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/FollowingDashboard/Views/HomeFollowingContentView.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/FollowingDashboard/Views/HomeFollwoingProfileView.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/HomeInteractor.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/HomeViewController.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/HotPlaceDashboard/HomeHotPlaceDashboardViewController.swift
* #62 
* @junbok97 님 공통으로 사용하기에 UI가 조금 달라서 애매해서 못넣었습니다 ㅜ ㅅ ㅜ
* 팔로잉 UI 추가
https://github.com/boostcampwm2023/iOS04-HeatPick/assets/74225754/9162be8b-60ff-4cb6-8142-67e966dcce1c
> Home Following UI 추가

- client/Targets/Presentation/Home/Implementations/Sources/Home/FriendDashboard/HomeFriendDashboardBuilder.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/FriendDashboard/HomeFriendDashboardInteractor.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/FriendDashboard/HomeFriendDashboardRouter.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/FriendDashboard/HomeFriendDashboardViewController.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/FriendDashboard/Views/HomeFriendContentView.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/HomeBuilder.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/HomeInteractor.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/HomeRouter.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/HomeViewController.swift
* close #62 
* 상황에 따라 친구 추천UI가 있거나 없을 수 있어서 attach 할 때 insert해서 특정 위치에 넣도록 구현했습니다.
* 친구 추천 UI 추가
https://github.com/boostcampwm2023/iOS04-HeatPick/assets/74225754/17d2da29-7399-4aa8-99fa-418a21be1699
> Home 친구 추천 UI 추가

- client/Targets/DesignSystem/DesignKit/Sources/Extensions/UICollectionView+.swift
- client/Targets/DesignSystem/DesignKit/Sources/Extensions/UITableViewCell+.swift
- client/Targets/DesignSystem/DesignKit/Sources/Views/ShowAllTableHeaderView.swift
- #128 
- extension TableView 수정
- extension CollectioView 수정
- ShowAllTableViewHeader 추가
> ShowAllTableHeader 추가

- client/Targets/Presentation/Home/Implementations/Sources/Home/HomeBuilder.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/HomeInteractor.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/HomeRouter.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/HomeRouterComponent.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/HomeRouterDependency.swift
- client/Targets/Presentation/Home/Implementations/Sources/SeeAll/HotPlace/HotPlaceSeeAllBuilder.swift
- client/Targets/Presentation/Home/Implementations/Sources/SeeAll/HotPlace/HotPlaceSeeAllInteractor.swift
- client/Targets/Presentation/Home/Implementations/Sources/SeeAll/HotPlace/HotPlaceSeeAllRouter.swift
- client/Targets/Presentation/Home/Implementations/Sources/SeeAll/Recommend/RecommendSeeAllInteractor.swift
* close #130 
* 추천 장소 모두 보기와 흡사하여 따로 스크린샷 첨부하지 않았습니다.
* 다른 부분은 NavigationView 타이틀 빼고는 동일합니다
* 핫플레이스 모두 보기 UI 추가
> 핫플레이스 모두 보기 추가

- README.md
* close #122 
* 첨부된 이미지가 프로젝트 소개로 들어갑니다.
* 프로젝트 소개 추가
> 프로젝트 소개 추가

- server/package-lock.json
- server/package.json
- server/src/story/dto/story.update.dto.ts
- server/src/story/story.controller.ts
- server/src/story/story.service.ts
- server/src/user/user.repository.ts
- server/src/util/util.create.story.entity.ts
- server/src/util/util.save.image.local.ts
#134 
*  Story Update API 추가
* class-validator class-transform 으로 DTO 검증
> Story Update API 추가

- server/package-lock.json
- server/package.json
- server/src/story/dto/story.update.dto.ts
- server/src/story/story.controller.ts
- server/src/story/story.service.ts
- server/src/user/user.repository.ts
- server/src/util/util.create.story.entity.ts
- server/src/util/util.save.image.local.ts
#138 
*  Story 삭제 기능 추가 ( soft delete )
> Story 삭제 API 추가

- README.md
* close #145 
* 기술 선택 과정에 대한 내용 추가
> 기술 선택 과정 READ ME 추가

- client/Targets/DesignSystem/DesignKit/Sources/Constants/Constants.swift
- client/Targets/DesignSystem/DesignKit/Sources/Views/NavigationView.swift
* close #150 
* NavigationViewButton 크기 변경
|AS-IS|TO-BE|
|--|--|
|![Simulator Screenshot - iPhone 15 - 2023-11-19 at 18 37 25](https://github.com/boostcampwm2023/iOS04-HeatPick/assets/74225754/d3b38c7b-60a3-41c1-9748-a29286dddbad)|![Simulator Screenshot - iPhone 15 - 2023-11-19 at 18 44 11](https://github.com/boostcampwm2023/iOS04-HeatPick/assets/74225754/4387b594-be7e-4c63-8ba4-8736dcde5ae7)|
> NavigationViewButton 크기 변경

- .github/workflows/test-actions.yml
- server/src/auth/auth.controller.ts
- server/src/entities/search.entity.ts
- server/src/entities/story.entity.ts
- server/src/entities/user.entity.ts
- server/src/search/search.controller.ts
- server/src/story/story.controller.ts
- server/src/story/story.service.ts
* close #147 
- 로그인/회원가입 기능의 swagger response 명세를 상세화 하였습니다.
- 검색 기능의 swagger response 명세를 상세화 하였습니다.
* Before-After 스크린샷 넣기
> Swagger API 명세 수정

- server/package-lock.json
- server/package.json
- server/src/entities/place.entity.ts
- server/src/entities/story.entity.ts
- server/src/place/dto/location.dto.ts
- server/src/place/place.controller.ts
- server/src/place/place.module.ts
- server/src/place/place.provider.ts
- server/src/place/place.service.ts
- server/src/search/search.controller.ts
- server/src/search/search.module.ts
- server/src/search/search.service.ts
- server/src/search/trie/placeTrie.ts
- server/src/search/trie/trieNode/placeTrieNode.ts
- server/src/story/story.service.ts
- server/src/util/util.haversine.ts
close #152 
- 위도, 경도를 바탕으로 반경 2km 내의 장소 객체를 리턴합니다.(haversine 공식 활용)
-  signin 시 데이터 리턴 형태를 수정하였습니다.
> 위치 기반 장소 리턴 기능 구현

- server/src/auth/auth.controller.ts
- signin의 리턴 JSON 데이터 형태를 변경하였습니다.
> signin 리턴 형태 변경

- server/src/auth/auth.controller.ts
- server/src/image/image.service.ts
* #158 
- signup 리턴 데이터 형태 수정
- signin 리턴 데이터 형태 수정
- 이미지 저장 시 해당 경로가 없는 경우 생성
> 로그인, 회원가입 리턴 타입 수정, 이미지 폴더 생성

- server/src/auth/auth.service.ts
* #158 
- 회원가입 시, 이미지가 없는 경우도 가능하게 변경
> 이미지 없는 경우 예외처리

- server/src/entities/comment.entity.ts
- server/src/entities/story.entity.ts
- server/src/entities/user.entity.ts
* close #161 
- 댓글 기능 구현 전, 댓글 Entity를 정의
- User, Story와의 연관 관계 설정
>  Comment Entity 정의 및 연관 관계 설정

- client/Targets/Presentation/Story/Implementations/Sources/StoryEditor/StoryEditorViewController.swift
* #53
* #143 
* 스크롤 시 키보드가 사라지도록 수정
* 저장하기 버튼을 stackView에서 빼고 키보드가 올라왔을 때 버튼 위치가 키보드 위로 따라 올라가도록 구현할지 고민중입니다.
> scroll 시 keyboard가 dismiss 되도록 수정

- server/src/app.module.ts
- server/src/comment/comment.controller.ts
- server/src/comment/comment.module.ts
- server/src/comment/comment.service.ts
- server/src/comment/dto/commnet.create.dto.ts
- server/src/entities/comment.entity.ts
- server/src/entities/story.entity.ts
- server/src/story/story.controller.ts
- server/src/story/story.service.ts
- server/src/util/util.create.comment.entity.ts
#167 
* 댓글 생성 API 구현
* Story Entity에 Comment Cascade 속성 추가
> 댓글 생성 API 구현

- server/src/app.module.ts
- server/src/comment/comment.controller.ts
- server/src/comment/comment.module.ts
- server/src/comment/comment.service.ts
- server/src/comment/dto/comment.update.dto.ts
- server/src/comment/dto/commnet.create.dto.ts
- server/src/entities/comment.entity.ts
- server/src/entities/story.entity.ts
- server/src/story/story.controller.ts
- server/src/story/story.service.ts
- server/src/util/util.create.comment.entity.ts
#171 
* 댓글 수정 API 구현
* DTO에 validation pipe 및 transform 적용
> 댓글 수정 API 구현

- server/src/app.module.ts
- server/src/comment/comment.controller.ts
- server/src/comment/comment.module.ts
- server/src/comment/comment.service.ts
- server/src/comment/dto/comment.delete.dto.ts
- server/src/comment/dto/comment.update.dto.ts
- server/src/comment/dto/commnet.create.dto.ts
- server/src/entities/comment.entity.ts
- server/src/entities/story.entity.ts
- server/src/story/story.controller.ts
- server/src/story/story.service.ts
- server/src/util/util.create.comment.entity.ts
> Comment 삭제 기능 구현

- server/src/app.module.ts
- server/src/comment/comment.controller.ts
- server/src/comment/comment.module.ts
- server/src/comment/comment.service.ts
- server/src/comment/dto/comment.delete.dto.ts
- server/src/comment/dto/comment.update.dto.ts
- server/src/comment/dto/commnet.create.dto.ts
- server/src/db/database.providers.ts
- server/src/entities/comment.entity.ts
- server/src/entities/story.entity.ts
- server/src/story/dto/story.create.dto.ts
- server/src/story/dto/story.update.dto.ts
- server/src/story/story.controller.ts
- server/src/story/story.module.ts
- server/src/story/story.service.ts
- server/src/story/type/story.user.data.ts
- server/src/util/util.create.comment.entity.ts
- server/src/util/util.create.story.entity.ts
- server/src/util/util.date.format.to.ISO8601.ts
#178 
* Story Category 는 1개만 설정하도록 변경
* 가상 유저가 아닌 실제 유저의 token으로 유저 정보를 받아오도록 수정
> Story 스키마 및 로직 수정

- server/src/entities/badge.entity.ts
- server/src/entities/user.entity.ts
- server/src/story/story.controller.ts
* close #185 
- Badge Entity 정의
- User Entity 연관 관계 설정
> feat: Badge Entity 정의 및 연관관계 설정

- client/Targets/App/Sources/AppRoot/AppRootComponent.swift
- client/Targets/Core/Network/NetworkAPIKit/Sources/Extensions/Encodable+Data.swift
- client/Targets/Data/Network/Home/Sources/DTO/RecommendLocationRequestDTO.swift
- client/Targets/Data/Network/Home/Sources/DTO/RecommendLocationResponseDTO.swift
- client/Targets/Data/Network/Home/Sources/DTO/RecommendResponseDTO.swift
- client/Targets/Data/Network/Home/Sources/HomeAPI.swift
- client/Targets/Data/Network/Home/Sources/dummy.swift
- client/Targets/Data/Repositories/Sources/HomeRepository.swift
- client/Targets/Domain/Entities/Sources/Home/RecommendStory.swift
- client/Targets/Domain/Interfaces/Sources/Repository/HomeRepositoryInterface.swift
- client/Targets/Domain/Interfaces/Sources/UseCase/Home/HomeUseCaseInterface.swift
- client/Targets/Domain/Interfaces/Sources/UseCase/Home/HotPlaceUseCaseInterface.swift
- client/Targets/Domain/Interfaces/Sources/UseCase/Home/RecommendUseCaseInterface.swift
- client/Targets/Domain/Interfaces/Sources/UseCase/HomeUseCaseInterface.swift
- client/Targets/Domain/UseCases/Sources/HomeUseCase.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/HomeBuilder.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/HotPlaceDashboard/HomeHotPlaceDashboardBuilder.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/HotPlaceDashboard/HomeHotPlaceDashboardInteractor.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/RecommendDashboard/HomeRecommendDashboardBuilder.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/RecommendDashboard/HomeRecommendDashboardInteractor.swift
* #177 
* 몇몇 부족한 요청이 있어서 추후 서버와 맞춰볼 예정입니다.
* Home Presentation 내부에 추천 장소와 핫플레이스에 대한 Interactor가 각각 있어서 UseCase도 프로토콜로 나눠준 후 주입은 HomeUseCase 하나로 하도록 하였습니다.
* HomeUseCase가 HotPlaceUseCase, RecommendUseCase를 준수하도록 구현한 후 각각 Interactor에 필요한 부분만 열어줬습니다.
* 추천 장소 API 추가
* 핫플레이스 API 추가
> 추천 장소, 핫플레이스 API 추가

- client/Targets/App/Sources/App/AppDelegate.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchHome/SearchHomeBuilder.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchHome/SearchHomeInteractor.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchHome/SearchHomeRouter.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchHome/SearchHomeViewController.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchHomeList/SearchHomeListInteractor.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchMap/SearchMapBuilder.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchMap/SearchMapInteractor.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchMap/SearchMapRouter.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchMap/SearchMapViewController.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchResult/BeginEditingTextDashboard/BeginEditingTextDashboardBuilder.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchResult/BeginEditingTextDashboard/BeginEditingTextDashboardInteractor.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchResult/BeginEditingTextDashboard/BeginEditingTextDashboardRouter.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchResult/BeginEditingTextDashboard/BeginEditingTextDashboardViewController.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchResult/BeginEditingTextDashboard/View/BeginEditingCollectionHeaderView.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchResult/BeginEditingTextDashboard/View/CategoryCollectionViewCell.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchResult/BeginEditingTextDashboard/View/RecentSearchTextCollectionViewCell.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchResult/EditingTextDashboard/EditingTextDashboardBuilder.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchResult/EditingTextDashboard/EditingTextDashboardInteractor.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchResult/EditingTextDashboard/EditingTextDashboardRouter.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchResult/EditingTextDashboard/EditingTextDashboardViewController.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchResult/EndEditingTextDashboard/EndEditingTextDashboardBuilder.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchResult/EndEditingTextDashboard/EndEditingTextDashboardInteractor.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchResult/EndEditingTextDashboard/EndEditingTextDashboardRouter.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchResult/EndEditingTextDashboard/EndEditingTextDashboardViewController.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchResult/SearchResultBuilder.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchResult/SearchResultInteractor.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchResult/SearchResultRouter.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchResult/SearchResultViewController.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchResult/Views/SearchNavigationView.swift
- #51 
- Appdelegate에서 네이버 맵 인증
- 검색어 비어있을 때 보여줄 리블렛 추가
- 검색어 입력시 보여줄 리블렛 추가
- 검색어 입력 완료시 보여줄 리블렛 추가
- 추후 uicollectionViewDataSource를 snapshot으로 변경 예정입니다.
- 검색화면 로직을 고민하느라 어쩌다 보니 massive PR이 되어버렷네용 ...
- 성준님이 의견주신대로 isHidden으로 변경
- 빨간화면과 초록화면 구현예쩡
https://github.com/boostcampwm2023/iOS04-HeatPick/assets/71696675/1bff4285-3123-48dd-828e-29f018a22cdd
> 검색어 빈칸일 때 UI 구현

- server/src/entities/badge.entity.ts
- server/src/util/util.save.image.local.ts
- 이미지 저장 시 폴더를 생성하기 위한 로직을 생성하여 반영하기 위해 PR을 작성합니다.
위와 같이 Postman을 통해 요청을 보내면, 생성된 스토리Id를 응답으로 받을 수 있습니다.
> 테스트를 위한 임시PR(폴더 생성 로직 구현)

- server/src/auth/auth.service.ts
- server/src/user/type/user.profile.detail.data.type.ts
- server/src/user/user.controller.ts
- server/src/user/user.repository.ts
- server/src/user/user.service.ts
#198 
* 사용자의 모든 Story 불러오기
user/story?userId={userId}
```json
[
{
"storyId": 3,
"title": "서울 경복궁",
"content": "경복궁 풍경입니다",
"likeCount": 21,
"createAt": "2023-11-15T10:55:04.000Z",
"__storyImages__": [],
"__comments__": [
{
"commentId": 6,
"content": "수"
}
]
},
{
"storyId": 4,
"title": "즉석떡볶이 맛집",
"content": "신전떡볶이보다 맛있어요!",
"likeCount": 11,
"createAt": "2023-11-15T10:55:04.000Z",
"__storyImages__": [],
"__comments__": []
},
{
"storyId": 5,
"title": "서울 맛집",
"content": "연남동 스시지현 진짜 맛집이에요",
"likeCount": 0,
"createAt": "2023-11-15T10:55:04.000Z",
"__storyImages__": [],
"__comments__": []
},
{
"storyId": 13,
"title": "title1213321213",
"content": "content",
"likeCount": 133,
"createAt": "2023-11-16T09:04:54.000Z",
"__storyImages__": [
{
"imageId": 22,
"imageUrl": …
```
> 사용자의 모든 Story 불러오기

- server/src/story/dto/story.create.dto.ts
- server/src/story/story.controller.ts
- server/src/story/story.service.ts
* #213 
* Story에서 JWT 검증 로직 변경
> Story에서 JWT 검증 로직 변경

- server/src/story/dto/story.create.dto.ts
- server/src/story/story.controller.ts
> Story Swagger 수정

- server/src/user/user.controller.ts
* close #215 
- conflict 수정 이후 머지 과정에서 발생한 중괄호 삭제 버그를 수정하였습니다.
> 중괄호 삭제 버그 수정

- .github/workflows/test-actions.yml
- server/src/image/image.controller.ts
- server/src/util/util.create.story.entity.ts
- server/src/util/util.save.image.local.ts
* #226 
* Image의 경로가 아닌  이름 만을 주어 Image 요청 
* story Image 요청 => story/image?name=${name}
* profile Image 요청 => profile/image?name=${name}
> Image의 경로가 아닌  이름 만을 주어 Image 요청 

- .github/workflows/test-actions.yml
* docker 공유 폴더 설정 변경
* 
* docker 공유 폴더 설정 변경
> docker 공유 폴더 설정 변경

- .github/workflows/test-actions.yml
* docker 공유 파일 경로 수정
* docker 공유 파일 경로 수정
> docker 공유 파일 경로 수정

- .github/workflows/test-actions.yml
* docker 공유 폴더 경로 변경
* docker 공유 폴더 경로 변경
> docker 공유 폴더 경로 변경

- server/src/story/dto/story.update.dto.ts
- server/src/story/story.controller.ts
* #233 
* Story CRUD 리턴 타입 Swagger에 맞게 변경
> Story CRUD 리턴 타입 Swagger에 맞게 변경

- client/Targets/Core/Network/NetworkAPIKit/Sources/Extensions/Encodable+Data.swift
- client/Targets/Core/Network/NetworkAPIKit/Sources/Media.swift
- client/Targets/Core/Network/NetworkAPIKit/Sources/MultipartFormData.swift
- client/Targets/Core/Network/NetworkAPIKit/Sources/NetworkProvider.swift
- client/Targets/Data/Network/Story/Sources/DTO/NewStoryRequestDTO.swift
- client/Targets/Data/Network/Story/Sources/DTO/NewStoryResponseDTO.swift
- client/Targets/Data/Network/Story/Sources/DTO/PlaceDTO.swift
- client/Targets/Data/Network/Story/Sources/StoryAPI.swift
- client/Targets/Data/Network/Story/Sources/dummy.swift
- client/Targets/Data/Repositories/Sources/StoryRepository.swift
- client/Targets/Domain/Entities/Sources/Story/Story.swift
- client/Targets/Domain/Entities/Sources/Story/StoryContent.swift
- client/Targets/Domain/Interfaces/Sources/Repository/StoryRepositoryInterface.swift
- client/Targets/Domain/Interfaces/Sources/UseCase/StoryUseCaseInterface.swift
- client/Targets/Domain/UseCases/Sources/StoryUseCase.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryCreator/StoryCreatorBuilder.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryEditor/Components/AttributeField.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryEditor/Components/ImageSelector.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryEditor/Components/LocationPicker.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryEditor/StoryEditorBuilder.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryEditor/StoryEditorInteractor.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryEditor/StoryEditorViewController.swift
* #53 
* 스토리 에디터에서 저장 버튼을 누르면 스토리가 생성됩니다.
* 스토리 생성 API 연결
* NetworkProvider multipart form data 버그 수정
* 스토리 생성시 위치를 필수적으로 입력하도록 하였습니다.
* multipart form data 형식 고민
* 코드에 comment 남기겠습니다.
> 스토리 생성 API 연결

- client/Targets/Presentation/BasePresentation/Sources/Common/SeeAllButtonView.swift
- client/Targets/Presentation/BasePresentation/Sources/Common/SeeAllView.swift
- client/Targets/Presentation/BasePresentation/Sources/Story/Views/StorySmallView.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/FollowingDashboard/HomeFollowingDashboardViewController.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/FriendDashboard/HomeFriendDashboardViewController.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/HotPlaceDashboard/HomeHotPlaceDashboardViewController.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/RecommendDashboard/HomeRecommendDashboardViewController.swift
- client/Targets/Presentation/My/Implementations/Sources/MyPage/MyPageBuilder.swift
- client/Targets/Presentation/My/Implementations/Sources/MyPage/MyPageInteractor.swift
- client/Targets/Presentation/My/Implementations/Sources/MyPage/MyPageRouter.swift
- client/Targets/Presentation/My/Implementations/Sources/MyPage/StoryDashboard/MyPageStoryDashboardBuilder.swift
- client/Targets/Presentation/My/Implementations/Sources/MyPage/StoryDashboard/MyPageStoryDashboardInteractor.swift
- client/Targets/Presentation/My/Implementations/Sources/MyPage/StoryDashboard/MyPageStoryDashboardRouter.swift
- client/Targets/Presentation/My/Implementations/Sources/MyPage/StoryDashboard/MyPageStoryDashboardViewController.swift
* close #236 
* **공통 컴포넌트 추가 (스크린샷을 확인해주세요)** 
* BasePresentation에 StorySmallView 추가
* BasePresentation에 SeeAllView 추가 (기존에 Home에서 쓰는 것을 옮겼습니다)
* MyPage Story UI 추가
* 공통 컴포넌트 추가 (StorySmallView, SeeAllView)
* SeeAllView 사용법
```swift
let seeAllView = SeeAllView()
seeAllView.setup(model: .init(
title: "내가 쓴 스토리",
isButtonEnabled: true // false이면 모두 보기 버튼 노출되지 않음
))
````
* StorySmallView 사용법
```swift
let storyView = StorySmallView()
storyView.setup(model: .init(thumbnailImageURL: "URL", title: "타이틀", subtitle: "서브타이틀", likes: 3, comments: 4))
```
|SeeAllView|StorySmallView|
|---|---|
|<img width="481" alt="스크린샷 2023-11-22 오후 8 23 52" src="https://github.com/boostcampwm2023/iOS04-HeatPick/assets/74225754/8139e4bb-e9e3-4588-a67b-3aa9bfc0f304">|<img width="482" alt="스크린샷 …
> 마이페이지 내가 쓴 스토리 추가, Story 공통 컴포넌트 추가

- client/Targets/App/Sources/AppRoot/AppRootComponent.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryCreator/StoryCreatorBuilder.swift
* #245 
* 
* StoryCreator의 usecase와 repository dependency를 app root에서 받도록 수정
> StoryCreatorBuilder 모듈 dependency 이슈 수정

- client/Targets/Presentation/BasePresentation/Sources/Story/Views/StorySmallView.swift
- client/Targets/Presentation/My/Implementations/Sources/MyPage/MyPageBuilder.swift
- client/Targets/Presentation/My/Implementations/Sources/MyPage/MyPageInteractor.swift
- client/Targets/Presentation/My/Implementations/Sources/MyPage/MyPageRouter.swift
- client/Targets/Presentation/My/Implementations/Sources/MyPage/MyPageViewController.swift
- client/Targets/Presentation/My/Implementations/Sources/MyPage/StoryDashboard/MyPageStoryDashboardInteractor.swift
- client/Targets/Presentation/My/Implementations/Sources/MyPage/StoryDashboard/MyPageStoryDashboardViewController.swift
- client/Targets/Presentation/My/Implementations/Sources/MyPage/StoryDashboard/Views/MyPageStoryEmptyView.swift
- client/Targets/Presentation/My/Implementations/Sources/MyPage/UserDashboard/MyPageUserDashboardInteractor.swift
- client/Targets/Presentation/My/Implementations/Sources/MyPage/UserDashboard/MyPageUserDashboardViewController.swift
- client/Targets/Presentation/My/Implementations/Sources/MyPage/UserDashboard/Views/MyPageUserView.swift
- client/Targets/Presentation/My/Implementations/Sources/SeeAll/MyPageStory/MyPageStorySeeAllBuilder.swift
- client/Targets/Presentation/My/Implementations/Sources/SeeAll/MyPageStory/MyPageStorySeeAllInteractor.swift
- client/Targets/Presentation/My/Implementations/Sources/SeeAll/MyPageStory/MyPageStorySeeAllRouter.swift
* close #244 
* 마이페이지 Routing 로직 추가 (모두 보기만 attach, 나머지는 print만 해두었음)
* 마이페이지 모두 보기 추가
* 마이페이지 내가 쓴 스토리 비었을 때 화면 추가
https://github.com/boostcampwm2023/iOS04-HeatPick/assets/74225754/a5cef902-2710-4871-a5a2-863f8d461345
https://github.com/boostcampwm2023/iOS04-HeatPick/assets/74225754/369b6296-2e54-44e2-b038-a56a56980eb2
> 마이페이지 UI 구현

- server/src/place/dto/location.dto.ts
- server/src/story/story.controller.ts
* close #241 
- transform을 적용하여, 쿼리 파라미터 파싱 과정에서 number 자료형으로 변환될 수 있도록 하였습니다.
> location DTO에서 파라미터 number 형으로 변환 구현

- server/src/image/image.controller.ts
- server/src/user/dto/user.profile.detail.data.dto.ts
- server/src/user/dto/user.update.dto.ts
- server/src/user/user.controller.ts
- server/src/user/user.repository.ts
- server/src/user/user.service.ts
* #256 
* User Profile Swagger 수정
> User Profile Swagger 수정

- client/Targets/App/Sources/AppRoot/AppRootComponent.swift
- client/Targets/Data/Network/My/Sources/DTO/MyProfileResponseDTO.swift
- client/Targets/Data/Network/My/Sources/MyAPI.swift
- client/Targets/Data/Network/My/Sources/dummy.swift
- client/Targets/Data/Repositories/Sources/MyPageRepository.swift
- client/Targets/Domain/Entities/Sources/My/MyPage.swift
- client/Targets/Domain/Entities/Sources/My/MyPageProfile.swift
- client/Targets/Domain/Entities/Sources/My/MyPageStory.swift
- client/Targets/Domain/Interfaces/Sources/Repository/MyPageRepositoryInterface.swift
- client/Targets/Domain/Interfaces/Sources/UseCase/My/MyPageProfileUseCaseInterface.swift
- client/Targets/Domain/Interfaces/Sources/UseCase/My/MyPageStoryUseCaseInterface.swift
- client/Targets/Domain/Interfaces/Sources/UseCase/My/MyPageUseCaseInterface.swift
- client/Targets/Domain/UseCases/Sources/MyPageUseCase.swift
- client/Targets/Presentation/My/Implementations/Sources/MyPage/MyPageBuilder.swift
- client/Targets/Presentation/My/Implementations/Sources/MyPage/MyPageInteractor.swift
- client/Targets/Presentation/My/Implementations/Sources/MyPage/StoryDashboard/MyPageStoryDashboardBuilder.swift
- client/Targets/Presentation/My/Implementations/Sources/MyPage/StoryDashboard/MyPageStoryDashboardInteractor.swift
- client/Targets/Presentation/My/Implementations/Sources/MyPage/UserDashboard/MyPageUserDashboardBuilder.swift
- client/Targets/Presentation/My/Implementations/Sources/MyPage/UserDashboard/MyPageUserDashboardInteractor.swift
* close #249 
* 서버로 요청했는데 약간 안맞는 부분이 있어서 요고는 #250 에서 해결하겠습니다.
* MyPageService 추가 (UseCase/Repository)
* Presentation 연결
* 동작 방식
* MyPageUseCase는 MyPageProfile과 StoryUseCase 를 준수하도록 하였습니다.
* 하위 리블렛에는 각각 MyPageProfileUseCase와 MyPageStoryUseCase를 주입하였습니다.
https://github.com/boostcampwm2023/iOS04-HeatPick/assets/74225754/b074f86b-a47e-4547-846a-119d83645f70
> MyPage 서비스 추가

- server/src/image/image.controller.ts
* #258 
* image 전송을 buffer에서 png로 변경
> image 전송을 buffer에서 png로 변경

- server/src/image/image.controller.ts
- server/src/story/dto/story.detail.user.data.ts
- server/src/story/dto/story.detail.view.data.dto.ts
- server/src/story/story.controller.ts
- server/src/story/story.repository.ts
- server/src/story/story.service.ts
- server/src/story/type/story.detail.view.data.ts
- server/src/story/type/story.user.data.ts
> 스토리 상세 유저 정보 수정

- server/src/entities/user.entity.ts
- server/src/user/dto/follow.request.dto.ts
- server/src/user/user.controller.ts
- server/src/user/user.repository.ts
- server/src/user/user.service.ts
* close #260 
- 유저의 팔로우 기능을 구현하였습니다.
- 유저 Id를 기반으로 팔로우와 팔로워 목록을 리턴하는 기능을 구현하였습니다
- 언팔기능을 구현하였습니다.
> 유저 팔로우 / 언팔 기능 구현

- client/Targets/Presentation/Search/Implementations/Sources/SearchHome/SearchHomeRouter.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchHome/SearchHomeViewController.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchResult/SearchBeforeDashboard/SearchBeforeCategoryDashboard/SearchBeforeCategoryDashboardBuilder.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchResult/SearchBeforeDashboard/SearchBeforeCategoryDashboard/SearchBeforeCategoryDashboardInteractor.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchResult/SearchBeforeDashboard/SearchBeforeCategoryDashboard/SearchBeforeCategoryDashboardRouter.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchResult/SearchBeforeDashboard/SearchBeforeCategoryDashboard/SearchBeforeCategoryDashboardViewController.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchResult/SearchBeforeDashboard/SearchBeforeCategoryDashboard/Views/SearchBeforeCategoryDashboardCell.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchResult/SearchBeforeDashboard/SearchBeforeDashboardBuilder.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchResult/SearchBeforeDashboard/SearchBeforeDashboardInteractor.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchResult/SearchBeforeDashboard/SearchBeforeDashboardRouter.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchResult/SearchBeforeDashboard/SearchBeforeDashboardViewController.swift
- #272 
- 검색 카테고리의 리블렛을 분리하였습니다.
- 분리한 리블렛의 상위 리블렛과 연결하였습니다.
> 검색 카테고리 리블렛 분리

- client/Targets/Presentation/Search/Implementations/Sources/SearchResult/SearchAfterDashboard/SearchAfterDashboardInteractor.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchResult/SearchAfterDashboard/SearchAfterDashboardRouter.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchResult/SearchAfterDashboard/SearchAfterDashboardViewController.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchResult/SearchAfterDashboard/SearchAfterStoryDashboard/SearchAfterStoryDashboardInteractor.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchResult/SearchAfterDashboard/SearchAfterStoryDashboard/SearchAfterStoryDashboardViewController.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchResult/SearchAfterDashboard/SearchAfterStoryDashboard/Views/SearchAfterStoryView.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchResult/SearchAfterDashboard/SearchAfterUserDashboard/SearchAfterUserDashboardInteractor.swift
- client/Targets/Presentation/Search/Implementations/Sources/SearchResult/SearchAfterDashboard/SearchAfterUserDashboard/SearchAfterUserDashboardViewController.swift
- #276 
- 검색완료시 보여주는 UI를 약간 수정하였습니다.
- 리뷰 계속해서 요청해서 죄송합니다 ㅠㅠ 새벽에 요청하기에는 조금 그래서 ...
> Search/SearchAfter UI 미세 조정

- client/Targets/App/Sources/AppRoot/AppRootComponent.swift
- client/Targets/Data/Network/Story/Sources/URLProtocols/StoryURLProtocol.swift
* #290 
* 스토리 생성 API URLProtocol 추가
> StoryAPI URLProtocol 추가

- server/src/db/database.providers.ts
- server/src/entities/badge.entity.ts
- server/src/entities/story.entity.ts
- server/src/story/dto/detail/story.detail.story.data.ts
- server/src/story/story.repository.ts
- server/src/story/story.service.ts
- server/src/user/user.repository.ts
* #297 
* story-badge 연관 관계 수정
> story-badge 연관관계 수정

- client/Targets/Data/Network/Story/Sources/URLProtocols/StoryURLProtocol.swift
- client/Targets/Domain/Entities/Sources/Location/Location.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryDetail/Components/StoryLikesCommentsView.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryDetail/Components/StoryMapView.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryDetail/Components/UserBadgeView.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryDetail/StoryDetailInteractor.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryDetail/StoryDetailViewController.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryEditor/Components/LocationPickerView.swift
* #300 
* 스토리 상세에 네이버 지도를 추가했습니다.
* Constant 설정이 되어있지 않는 몇몇 값들을 Constant로 넣었습니다.
> 스토리 상세 지도 추가

- server/src/story/dto/detail/story.detail.story.data.ts
- server/src/story/story.service.ts
* #305 
* story detail에서 storyId 전달
> story detail에서 storyId 전달

- client/Targets/Data/Network/Story/Sources/DTO/AuthorResponseDTO.swift
- client/Targets/Data/Network/Story/Sources/DTO/StoryDetailResponseDTO.swift
- client/Targets/Data/Network/Story/Sources/DTO/StoryResponseDTO.swift
* #312 
* Response로만 받는 DTO에 ResponseDTO로 명시
> StoryAPI DTO 네이밍 수정

- server/src/place/place.service.ts
- server/src/search/dto/search.result.dto.ts
- server/src/search/dto/story.result.dto.ts
- server/src/search/dto/user.result.dto.ts
- server/src/search/search.controller.ts
- server/src/search/search.service.ts
- server/src/search/trie/historyTrie.ts
- server/src/search/trie/placeTrie.ts
- server/src/search/trie/storyTrie.ts
- server/src/search/trie/userTrie.ts
- server/src/story/story.service.ts
- server/src/user/user.service.ts
* close #310 
- 검색 시 검색어와 관련된 스토리와 유저를 5개씩 리턴합니다.
> 검색 전용 API 구현

- server/src/search/dto/story.result.dto.ts
- server/src/search/search.controller.ts
- server/src/user/dto/user.response.dto.ts
- server/src/user/user.controller.ts
- server/src/user/user.service.ts
- server/src/user/util/user.entity.to.obj.ts
- server/src/util/story.entity.to.obj.ts
- server/src/util/user.entity.to.obj.ts
* close #315 
- 검색 결과, 렌더링에 필요한 정보만 리턴되도록 수정하였습니다.
> 검색 결과 리턴 형태 수정

- server/src/user/user.service.ts
* close #320 
- 스토리 컨트롤러에 가드를 적용하고, 기존 디코딩 로직을 제거했습니다.
> 스토리 컨트롤러 가드 적용

- client/Targets/Presentation/Story/Implementations/Sources/StoryEditor/Components/LocationPickerView.swift
* #316 
* 스토리 생성 시 위치 선택 지도를 네이버 지도로 변경
> LocationPicker Naver 지도로 변경

- client/Targets/App/Sources/AppRoot/AppRootComponent.swift
- client/Targets/App/Sources/AppRoot/AppRootRouter.swift
- client/Targets/Data/Network/Story/Sources/DTO/StoryDetailRequestDTO.swift
- client/Targets/Data/Network/Story/Sources/StoryAPI.swift
- client/Targets/Data/Network/Story/Sources/URLProtocols/StoryURLProtocol.swift
- client/Targets/Data/Repositories/Sources/StoryRepository.swift
- client/Targets/Domain/Interfaces/Sources/Repository/StoryRepositoryInterface.swift
- client/Targets/Domain/Interfaces/Sources/UseCase/StoryUseCaseInterface.swift
- client/Targets/Domain/UseCases/Sources/StoryUseCase.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryCreator/StoryCreatorBuilder.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryCreator/StoryCreatorInteractor.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryCreator/StoryCreatorRouter.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryCreator/StoryCreatorViewController.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryDetail/StoryDetailBuilder.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryDetail/StoryDetailInteractor.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryDetail/StoryDetailRouter.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryDetail/StoryDetailViewController.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryEditor/StoryEditorBuilder.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryEditor/StoryEditorInteractor.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryEditor/StoryEditorRouter.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryEditor/StoryEditorViewController.swift
- client/Targets/Presentation/Story/Interfaces/Sources/Story.swift
- client/Targets/Presentation/Story/Interfaces/Sources/StoryInterface.swift
* #325 
* StoryDetail, StoryCreator, StoryEditor에 대한 interface 추가
* Implementation에서 public 제거
* Builder class와 Interface를 제외한 모든 리블렛 protocol과 class에서 public을 제거하였습니다.
> 스토리 interface 추가

- client/Targets/Core/CoreKit/Resources/APIResponseMock/Home/HomeRecommendLocationResponseMock.json
- client/Targets/Core/CoreKit/Resources/APIResponseMock/Home/HomeRecommendResponseMock.json
- client/Targets/Data/Network/Home/Sources/DTO/RecommendLocationResponseDTO.swift
- client/Targets/Data/Network/Home/Sources/DTO/RecommendResponseDTO.swift
- client/Targets/Data/Repositories/Sources/HomeRepository.swift
- client/Targets/Domain/Entities/Sources/Home/HotPlace.swift
- client/Targets/Domain/Entities/Sources/Home/RecommendStory.swift
- client/Targets/Domain/Interfaces/Sources/Repository/HomeRepositoryInterface.swift
- client/Targets/Domain/Interfaces/Sources/UseCase/Home/HotPlaceUseCaseInterface.swift
- client/Targets/Domain/UseCases/Sources/HomeUseCase.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/HotPlaceDashboard/HomeHotPlaceDashboardInteractor.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/RecommendDashboard/HomeRecommendDashboardInteractor.swift
* #219 
* 아직 완전히 API 연결 마무리가 아니라 이슈는 열어두겠습니다.
* HotPlace Entity 추가
* Recommend, RecommendLocation Response 변경
* 이에 따른 Mock JSON값 변경
> Home API 변경

- server/src/category/category.provider.ts
- server/src/category/category.repository.ts
- server/src/entities/category.entity.ts
- server/src/entities/story.entity.ts
- server/src/story/dto/story.create.dto.ts
- server/src/story/dto/story.create.meta.dto.ts
- server/src/story/dto/story.update.dto.ts
- server/src/story/story.controller.ts
- server/src/story/story.module.ts
- server/src/story/story.service.ts
- server/src/util/util.create.story.entity.ts
* #331 
* 스토리 생성 시 필요한 데이터 가져오기
* category-story 연관관계 수정
* /story/meta
```json
{
"badgeList": [
{
"badgeId": 1,
"badgeName": "뉴비"
}
],
"categoryList": [
{
"categoryId": 1,
"categoryName": "맛집"
},
{
"categoryId": 2,
"categoryName": "카페"
}
]
}
```
> 스토리 생성 시 필요한 데이터 가져오기

- server/src/entities/badge.entity.ts
- server/src/story/story.module.ts
- server/src/story/story.service.ts
- server/src/user/user.controller.ts
- server/src/user/user.service.ts
* close #339 
- 스토리 생성 시, 등록한 뱃지의 경험치를 증가시키도록 구현하였습니다.
> 스토리 생성 시 뱃지 경험치 증가 구현

- server/src/user/dto/user.profile.detail.data.dto.ts
- server/src/user/dto/user.profile.detail.story.dto.ts
- server/src/user/dto/user.update.dto.ts
- server/src/user/user.controller.ts
- server/src/user/user.service.ts
#338 
* 사용자의 Profile를 불러오는 로직 수정
> 사용자의 Profile를 불러오는 로직 수정

- server/src/story/dto/story.create.meta.dto.ts
- server/src/story/story.service.ts
* #345 
* 스토리 생성 시 필요한 데이터 필드 수정
* categoryList -> categories, badgeList -> badges
> 스토리 생성 시 필요한 데이터 필드 수정

- client/Targets/App/Sources/App/AppDelegate.swift
- client/Targets/App/Sources/AppRoot/AppRootComponent.swift
- client/Targets/Data/Repositories/Sources/LocationService.swift
- client/Targets/Domain/Entities/Sources/Home/RecommendPlace.swift
- client/Targets/Domain/Interfaces/Sources/Repository/LocationServiceInterface.swift
- client/Targets/Domain/Interfaces/Sources/UseCase/Home/RecommendUseCaseInterface.swift
- client/Targets/Domain/Interfaces/Sources/UseCase/Search/SearchMapUseCaseInterface/SearchMapUseCaseInterface.swift
- client/Targets/Domain/UseCases/Sources/HomeUseCase.swift
- client/Targets/Domain/UseCases/Sources/SearchUseCase.swift
- client/Targets/Presentation/BasePresentation/Sources/Common/AdaptivePresentationControllerDelegateAdapter.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/RecommendDashboard/HomeRecommendDashboardInteractor.swift
- client/Targets/Presentation/Search/Implementations/Sources/Search/SearchBuilder.swift
- client/Targets/Presentation/Search/Implementations/Sources/Search/SearchInteractor.swift
- client/Targets/Presentation/Search/Implementations/Sources/Search/SearchMap/SearchMapBuilder.swift
- client/Targets/Presentation/Search/Implementations/Sources/Search/SearchMap/SearchMapInteractor.swift
- client/Targets/Presentation/Search/Implementations/Sources/Search/SearchMap/SearchMapRouter.swift
- client/Targets/Presentation/Search/Implementations/Sources/Search/SearchMap/SearchMapViewController.swift
- client/Targets/Presentation/Search/Implementations/Sources/Search/SearchRouter.swift
- client/Targets/Presentation/Search/Implementations/Sources/Search/SearchViewController.swift
* close #321 
* **수정 내역 설명 코드에 적어두겠습니다**
* Home 화면 위치 정보 추가
* Dismiss Adapter 추가 (스크롤로 dismiss 되었을 때 사용하기 위한)
* 지도 Location 정보 추가
* SearchCurrentLocation 라우팅 변경
* 시뮬레이터에서 위치를 키거나 실제 기기에서 위치를 키면 테스트 가능
https://github.com/boostcampwm2023/iOS04-HeatPick/assets/74225754/3da19047-f133-461c-926a-f15cb05c4e4e
> 위치 정보 서비스 추가

- server/src/app.module.ts
* close #355 
- 한국을 제외한 IP source에서의 요청을 모두 차단합니다.
> IP 차단 미들웨어 작성

- server/src/auth/auth.service.ts
- server/src/image/image.service.ts
- server/src/util/util.create.story.entity.ts
* #353 
* 기존에 잘못된 경로로 저장되는 ImageURL 경로 변경
> image URL 경로 변경

- server/src/story/dto/detail/story.detail.story.data.ts
- server/src/story/dto/story.create.meta.dto.ts
- server/src/story/story.controller.ts
- server/src/story/story.service.ts
- server/src/user/dto/user.profile.detail.data.dto.ts
- server/src/user/user.controller.ts
- server/src/util/util.date.format.to.ISO8601.ts
* #352 
* 
* Story을 가져올 시 날짜 형식을 ISO8601로 변경
```json
"createdAt": "2023-11-20T14:30:00Z",
```
> Story을 가져올 시 날짜 형식을 ISO8601로 변경

- client/Targets/Presentation/Story/Implementations/Sources/StoryDetail/Components/StoryImagesView.swift
* #54 
* 이미지 UI가 틀어지는 부분이 있어 수정했습니다.
> 스토리 상세 이미지 view 수정

- client/Targets/App/Sources/AppRoot/AppRootComponent.swift
- client/Targets/Core/CoreKit/Resources/APIResponseMock/My/MyProfileResponseMock.json
- client/Targets/Data/Network/My/Sources/DTO/MyProfileResponseDTO.swift
- client/Targets/Data/Network/My/Sources/MyAPI.swift
- client/Targets/Domain/Entities/Sources/My/MyPage.swift
- client/Targets/Domain/Entities/Sources/My/MyPageBadge.swift
- client/Targets/Domain/Entities/Sources/My/MyPageProfile.swift
- client/Targets/Domain/UseCases/Sources/MyPageUseCase.swift
- client/Targets/Presentation/My/Implementations/Sources/MyPage/MyPageInteractor.swift
- client/Targets/Presentation/My/Implementations/Sources/MyPage/UserDashboard/MyPageUserDashboardInteractor.swift
* close #250 
* 마이페이지에 뱃지 들어간 부분 수정했습니다.
* 마이페이지 API 연결
> 마이페이지 프로필 뱃지 추가

- client/Targets/Presentation/Search/Implementations/Sources/Search/SearchResult/SearchAfterDashboard/SearchAfterDashboardInteractor.swift
- client/Targets/Presentation/Search/Implementations/Sources/Search/SearchResult/SearchAfterDashboard/SearchAfterStoryDashboard/SearchAfterStoryDashboardInteractor.swift
- client/Targets/Presentation/Search/Implementations/Sources/Search/SearchResult/SearchAfterDashboard/SearchAfterStoryDashboard/SearchAfterStoryDashboardViewController.swift
- client/Targets/Presentation/Search/Implementations/Sources/Search/SearchResult/SearchAfterDashboard/SearchAfterUserDashboard/SearchAfterUserDashboardInteractor.swift
- client/Targets/Presentation/Search/Implementations/Sources/Search/SearchResult/SearchAfterDashboard/SearchAfterUserDashboard/SearchAfterUserDashboardViewController.swift
- client/Targets/Presentation/Search/Implementations/Sources/Search/SearchResult/SearchBeforeDashboard/SearchBeforeDashboardInteractor.swift
- client/Targets/Presentation/Search/Implementations/Sources/Search/SearchResult/SearchBeforeDashboard/SearchBeforeDashboardRouter.swift
- client/Targets/Presentation/Search/Implementations/Sources/Search/SearchResult/SearchBeforeDashboard/SearchBeforeDashboardViewController.swift
- client/Targets/Presentation/Search/Implementations/Sources/Search/SearchResult/SearchBeforeDashboard/SearchBeforeRecentSearchesDashboard/SearchBeforeRecentSearchesDashboardInteractor.swift
- client/Targets/Presentation/Search/Implementations/Sources/Search/SearchResult/SearchBeforeDashboard/SearchBeforeRecentSearchesDashboard/SearchBeforeRecentSearchesDashboardViewController.swift
- client/Targets/Presentation/Search/Implementations/Sources/Search/SearchResult/SearchBeforeDashboard/SearchBeforeRecentSearchesDashboard/Views/SearchBeforeRecentSearchesView.swift
- client/Targets/Presentation/Search/Implementations/Sources/Search/SearchResult/SearchResultInteractor.swift
- client/Targets/Presentation/Search/Implementations/Sources/Search/SearchResult/SearchResultRouter.swift
- client/Targets/Presentation/Search/Implementations/Sources/Search/SearchResult/SearchResultViewController.swift
- client/Targets/Presentation/Search/Implementations/Sources/Search/SearchResult/SearchingDashboard/SearchingDashboardInteractor.swift
- client/Targets/Presentation/Search/Implementations/Sources/Search/SearchResult/Views/SearchNavigationView.swift
- #309
- 메모리 leak 해결
- 최근 검색어 선택시 비지니스 로직 구현
https://github.com/boostcampwm2023/iOS04-HeatPick/assets/71696675/b041a039-d471-4576-9bf1-da723751bd33
> 순환참조 해결 및 최근검색어 로직 구현

- server/src/util/story.entity.to.obj.ts
* close #371 
* 스토리 추천 시, 유저의 정보도 리턴하도록 변경하였습니다.
> 추천 스토리 리턴 시, 리턴 형태 변경

- server/src/comment/comment.service.ts
- server/src/entities/story.entity.ts
- server/src/entities/user.entity.ts
- server/src/story/story.controller.ts
- server/src/story/story.repository.ts
- server/src/story/story.service.ts
* #384 
* 스토리 좋아요 추가, 좋아요 취소 구현
* 좋아요 추가 POST /story/like?storyId={storyId}
* 좋아요 취소 POST /story/unlike?storyId={storyId}
> 스토리 좋아요 추가, 좋아요 취소 구현

- server/src/comment/comment.service.ts
- server/src/entities/story.entity.ts
- server/src/entities/user.entity.ts
- server/src/story/dto/detail/story.detail.story.data.ts
- server/src/story/story.controller.ts
- server/src/story/story.repository.ts
- server/src/story/story.service.ts
- server/src/user/dto/user.profile.detail.story.dto.ts
- server/src/user/user.controller.ts
- server/src/user/user.service.ts
* #390 
* 스토리 상세, 프로필에 좋아요 누른 상태 구현
* 좋아요를 눌렀으면 0, 아니면 1
> 스토리 상세, 프로필에 좋아요 누른 상태 구현

- server/src/comment/comment.service.ts
- server/src/entities/story.entity.ts
- server/src/entities/user.entity.ts
- server/src/story/dto/detail/story.detail.story.data.ts
- server/src/story/story.controller.ts
- server/src/story/story.repository.ts
- server/src/story/story.service.ts
- server/src/user/dto/user.profile.detail.story.dto.ts
- server/src/user/user.controller.ts
- server/src/user/user.service.ts
- server/src/util/util.story.update.ts
* #393 
* 기존 스토리를 수정하는 것으로 변경 -> 이미 연관되어있는 댓글, 좋아요 때문에 변경
> 스토리 수정 재구현

- client/Targets/App/Info.plist
- client/Targets/Presentation/Search/Implementations/Sources/Search/SearchInteractor.swift
* close #399 
* 컴파일 에러가 나서 빠르게 추가했습니다.
* Extension 에러 수정
* Appearance 추가
> Extension 수정, Appearance 추가

- server/src/user/dto/user.profile.detail.data.dto.ts
- server/src/user/user.controller.ts
- server/src/user/user.service.ts
* 프로필 상세 팔로우 데이터 확인 추가
```json
{
"userId": 3,
"username": "기검",
"profileURL": "https://server.bc8heatpick.store/image/profile?name=",
"isFollow": 0, //0 은 팔로우한 상태, 1은 안 한 상태
"temperature": 0,
"temperatureFeeling": "🧊 차가워요",
"followerCount": 1,
"storyCount": 0,
"experience": 0,
"maxExperience": 999,
"mainBadge": {
"badgeId": 2,
"badgeName": "뉴비",
"badgeExp": 0,
"emoji": "🍼"
},
"badgeExplain": "저는 아무 것도 모르는 뉴비에요",
"storyList": []
}
```
> 프로필 상세 팔로우 데이터 확인 추가

- server/src/story/story.service.ts
- server/src/user/dto/response/profile.update.meta.badge.data.ts
- server/src/user/dto/response/profile.update.meta.dto.ts
- server/src/user/dto/user.profile.detail.data.dto.ts
- server/src/user/user.controller.ts
- server/src/user/user.service.ts
* #406 
* 프로필 업데이트를 위한 데이터 요청
```json
{
"userId": 1,
"profileImageURL": "https://server.bc8heatpick.store/image/profile?name=978f3c2c810d5ee1174e52386eb5edaab.png",
"username": "update sayho",
"nowBadge": {
"badgeId": 1,
"badgeName": "뉴비",
"badgeExp": 0,
"emoji": "🍼",
"badgeExplain": "저는 아무 것도 모르는 뉴비에요"
},
"badges": [
{
"badgeId": 1,
"badgeName": "뉴비",
"badgeExp": 0,
"emoji": "🍼",
"badgeExplain": "저는 아무 것도 모르는 뉴비에요"
}
]
}
```
> 프로필 업데이트를 위한 데이터 요청

- server/src/user/user.service.ts
> fix: 팔로우 버그 픽스

- server/src/user/user.controller.ts
- server/src/user/user.service.ts
* #423 
* profile에 story를 불러오는 로직 수정
* 스토리 모두 보기 시 offset, limit를 통해 페이징 구현
> profile에 story를 불러오는 로직 수정, 페이징 구현

- server/src/app.module.ts
- server/src/auth/auth.service.ts
- server/src/comment/comment.service.ts
- server/src/entities/user.entity.ts
- server/src/search/dto/story.result.dto.ts
- server/src/search/search.controller.ts
- server/src/story/story.controller.ts
- server/src/story/story.service.ts
- server/src/user/dto/user.response.dto.ts
- server/src/user/user.controller.ts
- server/src/user/user.service.ts
- server/src/util/story.entity.to.obj.ts
- server/src/util/user.entity.to.obj.ts
* close #431 
- 스토리 리턴 시 스토리의 좌표 정보도 리턴합니다.
- 팔로우/팔로워 조회 시 더 디테일한 정보를 리턴합니다
> 스토리 리턴 정보 추가

- server/src/app.module.ts
- server/src/comment/comment.controller.ts
- server/src/comment/dto/response/comment.mentionable.response.dto.ts
- server/src/comment/dto/response/comment.view.response.dto.ts
- server/src/entities/profileImage.entity.ts
- server/src/util/util.story.update.ts
* #434 
* story update 수정 및 ip차단 재적용
> story update 수정 및 ip차단 재적용

- client/Targets/Presentation/Story/Implementations/Sources/Comment/CommentViewController.swift
- client/Targets/Presentation/Story/Implementations/Sources/Comment/Components/CommentInputField.swift
- client/Targets/Presentation/Story/Implementations/Sources/Comment/Components/CommentTableViewCell.swift
* #419 
* 댓글 UI 구현
* PR를 볼 때 도움이 되는 항목 추가
> 댓글 화면 cell 및 입력 view UI 구현

- client/Targets/DesignSystem/DesignKit/Sources/Extensions/NSMutableAttributedString+.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/RecommendDashboard/Views/HomeRecommendContentView.swift
* close #441 
* 추천 장소 UI가 깨지는 이슈가 있어서 수정했습니다.
* 추천 장소에 이미지에 따라 텍스트가 잘 보이지 않아 stroke 추가했습니다.
* 추천 장소 높이 고정 값 추가
* 추천 장소 Text Stroke 추가
|AS-IS (Layout)|AS-IS (Text)|TO-BE|
|--|--|--|
|![IMG_5652](https://github.com/boostcampwm2023/iOS04-HeatPick/assets/74225754/a439d94e-13a3-4138-adf0-73654de298d7)|![IMG_5658](https://github.com/boostcampwm2023/iOS04-HeatPick/assets/74225754/8f6e5538-1f96-41da-8740-289a297c36d0)|![IMG_5659](https://github.com/boostcampwm2023/iOS04-HeatPick/assets/74225754/338cd428-3948-4658-89a6-ae26e55fe1d4)|
> 추천 장소 UI 수정

- client/Targets/Presentation/Auth/Implementations/Sources/LocationAuthority/LocationAuthorityBuilder.swift
- client/Targets/Presentation/Auth/Implementations/Sources/LocationAuthority/LocationAuthorityInteractor.swift
- client/Targets/Presentation/Auth/Implementations/Sources/LocationAuthority/LocationAuthorityRouter.swift
- client/Targets/Presentation/Auth/Implementations/Sources/LocationAuthority/LocationAuthorityViewController.swift
* close #407 
* 위치 권한 Bottom spacing 추가
|iPhone SE|iPhone 15|
|--|--|
|![image](https://github.com/boostcampwm2023/iOS04-HeatPick/assets/74225754/b1ff562e-efb3-4919-96c8-209d5181c06d)|![image](https://github.com/boostcampwm2023/iOS04-HeatPick/assets/74225754/aaf1c2ff-f67f-4bfc-b3a1-07f19578db8c)|
> 위치 권한 레이아웃 수정

- server/src/story/story.controller.ts
> import 경로 수정

- server/src/comment/comment.controller.ts
- server/src/comment/comment.service.ts
- server/src/comment/dto/request/comment.update.dto.ts
- server/src/comment/dto/response/comment.mentionable.response.dto.ts
- server/src/comment/dto/response/comment.view.response.dto.ts
- server/src/story/dto/request/story.create.request.dto.ts
- server/src/story/dto/request/story.update.request.dto.ts
- server/src/story/dto/response/detail/story.detail.view.data.response.dto.ts
- server/src/story/dto/response/story.create.meta.response.dto.ts
- server/src/story/story.controller.ts
- server/src/story/story.service.ts
- server/src/util/util.comment.update.ts
* #483 
* Story, Comment Response 수정
> Story, Comment Response 수정

- server/src/user/user.service.ts
* close #491
- 언팔로우에 await를 적용하여, 모든 로직이 종료되고 response가 가도록 적용했습니다.
> 언팔로우 비동기처리

- client/Targets/Domain/Entities/Sources/Comment/MentionUser.swift
- client/Targets/Presentation/Story/Implementations/Sources/Comment/CommentInteractor.swift
- client/Targets/Presentation/Story/Implementations/Sources/Comment/CommentViewController.swift
- client/Targets/Presentation/Story/Implementations/Sources/Comment/Components/CommentTableViewCell.swift
- client/Targets/Presentation/Story/Implementations/Sources/Comment/Components/MentioneeView.swift
*  #500 
* Mention 버튼을 눌러 mention 할 사람을 설정할 수 있도록 추가
*
> mention 기능 추가

- server/src/db/database.providers.ts
* close #509 
- DB 연결로 인해 자주 서버가 동작하지 않는 점을 개선하고자, timeout 옵션을 추가하였습니다.
> db 연결 관련 timeout 설정

- client/Targets/Core/CoreKit/Sources/CombineUtil/ActionPublisher.swift
- client/Targets/Core/CoreKit/Sources/CombineUtil/UIGestureRecognizer+Combine.swift
- client/Targets/Core/CoreKit/Sources/CombineUtil/UIView+Combine.swift
- client/Targets/Data/Network/Home/Sources/DTO/UserRecommendResponseDTO.swift
- client/Targets/Data/Network/Home/Sources/HomeAPI.swift
- client/Targets/Data/Repositories/Sources/HomeRepository.swift
- client/Targets/Domain/Entities/Sources/User/UserRecommend.swift
- client/Targets/Domain/Interfaces/Sources/Repository/HomeRepositoryInterface.swift
- client/Targets/Domain/Interfaces/Sources/UseCase/Home/HomeUseCaseInterface.swift
- client/Targets/Domain/Interfaces/Sources/UseCase/Home/UserRecommendUseCaseInterface.swift
- client/Targets/Domain/UseCases/Sources/HomeUseCase.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/FriendDashboard/HomeFriendDashboardBuilder.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/FriendDashboard/HomeFriendDashboardInteractor.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/FriendDashboard/HomeFriendDashboardViewController.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/FriendDashboard/Views/HomeFriendContentView.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/HomeBuilder.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/HomeInteractor.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/HomeViewController.swift
- client/Targets/Presentation/Home/Implementations/Tests/Sources/Home/HomeInteractorTests.swift
* close #502 
* 친구 추천을 했을 때 목록에 아무도 없으면 detach 시켰습니다.
* 현재는 단순히 출력만하고 있는데 추후 UserProfile 작업 완료되시면 라우팅까지 붙이겠습니다!
* Combine + UIGesture 추가
* 친구 추천 추가
* [참고](https://github.com/CombineCommunity/CombineCocoa/blob/main/Sources/CombineCocoa/Controls/UIGestureRecognizer%2BCombine.swift)
https://github.com/boostcampwm2023/iOS04-HeatPick/assets/74225754/9da48074-08a3-40f4-8160-cd3094c6574d
> 친구 추천, Combine+Gesture 추가

- client/Targets/Presentation/Search/Implementations/Sources/Search/SearchViewController.swift
* #close 514
* View를 세팅하는 순서가 달라 네이버 지도가 가장 상단에 가는 이슈가 있어 수정했습니다.
* 지도 레이아웃 계층 구조 수정
> 지도 레이아웃 계층 구조 수정

- client/Targets/Data/Network/Story/Sources/DTO/MetadataResponseDTO.swift
* #517 
* API response 구조 업데이트
> story/meta API 업데이트

- server/src/category/category.module.ts
- server/src/category/category.service.ts
- server/src/comment/comment.controller.ts
- server/src/comment/comment.module.ts
- server/src/comment/comment.service.ts
- server/src/comment/dto/request/comment.update.dto.ts
- server/src/entities/comment.entity.ts
- server/src/entities/story.entity.ts
- server/src/entities/user.entity.ts
- server/src/story/dto/response/story.create.meta.response.dto.ts
- server/src/story/story.controller.ts
- server/src/story/story.module.ts
- server/src/story/story.service.ts
- server/src/user/user.controller.ts
- server/src/user/user.module.ts
- server/src/user/user.service.ts
> 외부 repo 의존성 제거

- client/Targets/Core/FoundationKit/Sources/Alert/AlertType.swift
- client/Targets/Presentation/Story/Implementations/Sources/Comment/CommentInteractor.swift
- client/Targets/Presentation/Story/Implementations/Sources/Comment/CommentViewController.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryDetail/StoryDetailInteractor.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryDetail/StoryDetailViewController.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryEditor/StoryEditorInteractor.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryEditor/StoryEditorViewController.swift
* #520 
* 스토리 상세, 에디터, 댓글 alert 메세지 수정
* 현재 `MyPageInteractor`에 `storyDidDelete` method 추가가 필요합니다.
* conflict 날 것 같아서 빼고 PR 올립니다.
> 스토리 상세, 에디터, 댓글 alert 메세지 수정

- server/src/category/category.service.ts
- server/src/user/user.service.ts
> 트랜잭션 내에서는 비동기 처리

- server/src/user/user.controller.ts
> 유저 추천 시 access 토큰을 디코드하여 사용하게 변경

- server/src/category/category.controller.ts
- server/src/category/category.module.ts
- server/src/category/dto/response/get.category.return.dto.ts
* close #537 
* DB에 존재하는 카테고리 리스트를 리턴하는 API 구현
> 카테고리 리턴 기능 추가

- server/src/story/dto/response/story-create-response.dto.ts
- server/src/story/story.controller.ts
- server/src/story/story.service.ts
* #539 
* story 생성시 badge정보도 함께 응답
> story 생성시 badge정보도 함께 응답

- server/src/auth/auth.service.ts
* close #546 
* 네이버 대신 깃허브 OAuth 로그인으로 변경
> 깃허브 로그인 구현

- server/src/auth/auth.controller.ts
- server/src/auth/auth.service.ts
* close #549 
- 네이버와 깃허브 로그인 API를 분리하였습니다.
> 네이버/깃허브 로그인 분리

- client/Targets/Data/Network/Auth/Sources/AuthAPI.swift
- client/Targets/Data/Repositories/Sources/AuthRepository.swift
- client/Targets/Domain/Entities/Sources/Auth/SignInService.swift
- client/Targets/Domain/Interfaces/Sources/Repository/AuthRepositoryInterface.swift
- client/Targets/Domain/Interfaces/Sources/UseCase/AuthUseCaseInterface.swift
- client/Targets/Domain/UseCases/Sources/AuthUseCase.swift
- client/Targets/Presentation/Auth/Implementations/Sources/SignIn/SignInInteractor.swift
- client/Targets/Presentation/Auth/Implementations/Sources/SignIn/SignInRouter.swift
- client/Targets/Presentation/Auth/Implementations/Sources/SignUp/SignUpBuilder.swift
- client/Targets/Presentation/Auth/Implementations/Sources/SignUp/SignUpInteractor.swift
> Naver, GitHub 로그인 분리

- server/src/user/dto/request/user.delete.dto.ts
- server/src/user/dto/response/user.profile.detail.data.dto.ts
- server/src/user/user.controller.ts
- server/src/user/user.service.ts
* #559 
* 회원 탈퇴 swagger 수정, isFollow는 boolean값으로 변경
> 회원 탈퇴 swagger 수정, isFollow는 boolean값으로 변경 

- server/src/comment/comment.module.ts
- server/src/comment/comment.service.ts
* 게시글에 댓글이 달리면 알림이 가도록 구현
* 게시글에 댓글이 달리면 알림이 가도록 구현
> 게시글에 댓글이 달리면 알림이 가도록 구현

- server/src/entities/user.entity.ts
- server/src/user/user.service.ts
> 회원 탈퇴 시 재가입 가능하게 수정

- server/src/story/story.controller.ts
- server/src/story/story.service.ts
- server/src/user/user.service.ts
* #580 
* 회원 탈퇴 시 follower, following까지 반영
> 회원 탈퇴 시 follower, following까지 반영

- server/src/user/user.service.ts
* #583 
* 탈퇴 시 활동 내역 삭제 후 user정보 삭제
> 탈퇴 시 활동 내역 삭제 후 user정보 삭제

- client/Targets/Presentation/Home/Implementations/Sources/Home/HomeBuilder.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/HomeInteractor.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/HomeRouter.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/HomeRouterComponent.swift
- client/Targets/Presentation/Home/Implementations/Sources/Home/HomeRouterDependency.swift
* #593 
* 홈화면의 친구추천에서 유저를 눌러 프로필 화면으로 이동할 수 있도록 연결
> 홈 친구 추천에서 프로필 화면 연결

- server/src/story/dto/response/story-create-response.dto.ts
- server/src/story/story.service.ts
* #601 
* story 생성 시 badge이모티콘까지 badgename에 추가
> story 생성시 badge이모티콘까지 badgename에 추가

- client/Targets/Data/Network/Story/Sources/DTO/NewStoryResponseDTO.swift
- client/Targets/Data/Repositories/Sources/StoryRepository.swift
- client/Targets/Domain/Entities/Sources/User/BadgeExp.swift
- client/Targets/Domain/Interfaces/Sources/Repository/StoryRepositoryInterface.swift
- client/Targets/Domain/Interfaces/Sources/UseCase/StoryUseCaseInterface.swift
- client/Targets/Domain/UseCases/Sources/StoryUseCase.swift
- client/Targets/Presentation/Search/Implementations/Sources/Search/SearchRouter.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryCreateSuccess/Components/RollingCharView.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryCreateSuccess/Components/RollingNumberView.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryCreateSuccess/StoryCreateSuccessBuilder.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryCreateSuccess/StoryCreateSuccessInteractor.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryCreateSuccess/StoryCreateSuccessRouter.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryCreateSuccess/StoryCreateSuccessViewController.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryDetail/StoryDetailInteractor.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryEditor/StoryEditorBuilder.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryEditor/StoryEditorInteractor.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryEditor/StoryEditorRouter.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryEditor/StoryEditorViewController.swift
* #556 
* 스토리 작성 성공 화면 추가
* ~~fade-in / fade-out 적용에 난항을 겪고 있어 코어타임 전에 애니메이션 적용 화면만 먼저 PR 올립니다.~~
* 진행을 얼마 못해서 죄송하네요 😢 
* 추가했습니다!
https://github.com/boostcampwm2023/iOS04-HeatPick/assets/32038936/28bd2d05-95bd-4ea0-85ee-2b62978becdc
> 스토리 작성 성공 화면 추가

- server/src/comment/comment.service.ts
- server/src/story/story.controller.ts
- server/src/story/story.service.ts
- server/src/user/user.service.ts
* #605
* 비동기적 예외 수정
* 이미지 최대 5개까지 가능
* story 생성 시 뱃지 이모지 따로 분리
> 비동기적 예외 수정, 자잘한 버그 수정

- server/src/db/database.providers.ts
- server/src/story/story.service.ts
* close #578 
- 추천 스토리 기능에서 쿼리를 최적화 하였습니다.
- select로 필요한 정보만 조회
- 추천 게시물 캐싱
> 추천 스토리 쿼리 최적화

- server/src/search/search.controller.ts
- server/src/util/story.entity.to.obj.ts
* close #610 
- 탈퇴한 유저의 스토리는 검색되지 않습니다.
> 탈퇴한 유저 스토리 제거하여 리턴

- server/src/comment/comment.service.ts
- server/src/notification/notification.service.ts
- server/src/user/user.service.ts
* #617 
* FCM에서 에러가 나도 응답이 가도록 수정
> FCM에서 에러가 나도 응답이 가도록 수정

- client/Targets/Core/FoundationKit/Sources/UserDefaults/UserDefaults+Key.swift
- client/Targets/Domain/UseCases/Sources/AuthUseCase.swift
* close #622 
* 간략한 설명을 적어도 좋음
* 앱 새로 설치했을 때 재로그인 하도록 변경 (UserDefaults)
> 앱 새로 설치했을 때 재로그인 하도록 변경

- server/src/user/user.service.ts
* #625 
* Profile 수정 Image 없으면 기존 프로필 이미지 유지
> Profile 수정 Image 없으면 기존 프로필 이미지 유지

- server/src/story/story.service.ts
* close #624 
- 기존의 좋아요 기반 추천에서, 좋아요, 댓글수, 작성 날짜를 고려하여 추천하도록 변경
- 가중치는 다음과 같음
const likeWeight = 2;
const commentWeight = 2;
const timeWeight = 1 / (60 * 60 * 24);
> 글 작성 날짜, 좋아요, 댓글 수를 고려하여 추천하도록 변경

- client/Targets/Presentation/Story/Implementations/Sources/StoryDetail/Components/StoryHeaderView.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryDetail/StoryDetailViewController.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryEditor/StoryEditorInteractor.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryEditor/StoryEditorViewController.swift
* #631
* 저작 버튼 터치시 터치 불가능하게 변경
* 스토리 상세화면 레이아웃 수정
> 저장 버튼 연속 동작 버그 수정

- server/src/auth/auth.controller.ts
- server/src/auth/auth.service.ts
- server/src/entities/category.entity.ts
* close #628 
* 카테고리 설명란 추가
* 카테고리 설명 리턴
> 카테고리 설명도 리턴

- server/src/user/dto/response/user.profile.detail.data.dto.ts
- server/src/user/user.controller.ts
- server/src/user/user.service.ts
- server/src/util/util.string.to.badge.content.ts
* close #629 
- 프로필, 뱃지 정보 리턴 시 다음 뱃지 정보도 리턴
- 다음 뱃지가 없는 경우 null 리턴
> 다음 뱃지 정보도 리턴

- server/src/comment/dto/response/comment.view.response.dto.ts
> 탈퇴한 회원의 댓글 예외처리

- server/src/auth/auth.controller.ts
- server/src/auth/auth.service.ts
* close #637 
* 닉네임 중복 체크로 로직 변경
> 중복 체크에서 닉네임만 체크하도록 변경

- server/src/user/user.service.ts
> 삭제된 스토리까지 불러와 연관 해제

- client/Targets/Presentation/Story/Implementations/Sources/Comment/Components/CommentTableViewCell.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryDetail/Components/ImageCountButton.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryDetail/Components/StoryHeaderView.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryDetail/StoryDetailInteractor.swift
- client/Targets/Presentation/Story/Implementations/Sources/StoryDetail/StoryDetailViewController.swift
* #638 
* 본인 게시글의 좋아요 버튼 hpBlack으로 변경
* 스토리 상세 화면 당겨서 refresh 추가
* 탈퇴한 유저의 댓글이 있는 경우에 대한 API 수정 반영
> 스토리 상세 QA 수정

- server/src/search/search.controller.ts
- server/src/story/story.service.ts
* close #647 
* 스토리 검색 시 null story를 제거합니다.
> Null story 제거하고 리턴하도록 변경

- server/src/auth/auth.controller.ts
- server/src/search/search.controller.ts
- server/src/story/story.service.ts
>  null 스토리 제거

- server/src/entities/comment.entity.ts
- server/src/user/user.service.ts
* #645 
* 연관된 story, comment 제거
> 연관된 story, comment 제거

- server/src/auth/auth.service.ts
- server/src/entities/user.entity.ts
- server/src/user/user.service.ts
- server/src/util/calculate.temper.ts
* close #655 
- 온도 계산 로직 추가
- temperature 칼럼 제거
> temperature implementation

- client/Targets/Data/Network/My/Sources/DTO/MyProfileResponseDTO.swift
- client/Targets/Domain/Entities/Sources/My/MyProfile.swift
- client/Targets/Domain/Entities/Sources/My/Profile.swift
- client/Targets/Domain/Entities/Sources/My/UserProfile.swift
- client/Targets/Presentation/My/Implementations/Sources/MyProfile/UserDashboard/MyPageUserDashboardInteractor.swift
* #657 
* 온도 DTO를 double 형으로 변경
> 온도 API 변경 반영

- client/Targets/Presentation/My/Implementations/Sources/UserProfile/UserDashboard/UserProfileUserDashboardInteractor.swift
* #657 
* my page에만 반영해서 추가로 PR 올립니다.
> 다른 유저의 프로필에도 소수점 제거

- server/src/comment/comment.service.ts
> mention시 알림 요청 추가

- server/src/story/story.service.ts
- server/src/user/user.service.ts
- server/src/util/util.string.to.badge.content.ts
* close #667 
- Cron 시간 변경 => 10분마다 Trie 갱신
- 추천 스토리 리턴 방식 수정
- 칭호 설명, 이모지 추가
> fix demo bugs

- server/src/story/story.service.ts
- server/src/user/user.service.ts
* close #671 
- 뱃지 최대경험치 1000으로 변경
- 장소 추천 방식 변경(DB 자체에서 필터링)
> #671 feat/badge max and location recommend modify
