boostcampwm2023/iOS04-HeatPick

client/Targets/App/Sources/AppRoot/AppRootRouter.swift, client/Targets/Core/CoreKit/Sources/RIBsUtil/ViewControllable+Routing.swift, client/Targets/DesignSystem/DesignKit/Sources/Constants/Constants.swift, client/Targets/DesignSystem/DesignKit/Sources/Views/NavigationView.swift, client/Targets/Presentation/Auth/Implementations/Sources/Login/LoginInteractor.swift, client/Targets/Presentation/Auth/Implementations/Sources/Login/LoginRouter.swift, client/Targets/Presentation/Auth/Implementations/Sources/SignUp/SignUpInteractor.swift, client/Targets/Presentation/Auth/Implementations/Sources/SignUp/SignUpViewController.swift
* #28
* 기존에 테스트를 위해 Present 했던 SignUp 화면을 Navigation Push 로 변경
* ViewControllable NavigationPush 추가
* Login-SignUp Navigation 연결
* tuist fetch -> tuist generate -> 실행
https://github.com/boostcampwm2023/iOS04-HeatPick/assets/74225754/36e7eafa-7a1d-43d4-a0ef-89f6283b78d4
=> Navigation Routing 추가

client/Targets/DesignSystem/DesignKit/Sources/Buttons/ActionButtonStyle.swift, client/Targets/DesignSystem/DesignKit/Sources/Extensions/UIView+.swift, client/Targets/Presentation/Home/Demo/Sources/AppDelegate.swift, client/Targets/Presentation/Home/Implementations/Sources/Home/FollowingDashboard/HomeFollowingDashboardBuilder.swift, client/Targets/Presentation/Home/Implementations/Sources/Home/FollowingDashboard/HomeFollowingDashboardInteractor.swift, client/Targets/Presentation/Home/Implementations/Sources/Home/FollowingDashboard/HomeFollowingDashboardRouter.swift, client/Targets/Presentation/Home/Implementations/Sources/Home/FollowingDashboard/HomeFollowingDashboardViewController.swift, client/Targets/Presentation/Home/Implementations/Sources/Home/HomeBuilder.swift, client/Targets/Presentation/Home/Implementations/Sources/Home/HomeInteractor.swift, client/Targets/Presentation/Home/Implementations/Sources/Home/HomeRouter.swift, client/Targets/Presentation/Home/Implementations/Sources/Home/HomeViewController.swift, client/Targets/Presentation/Home/Implementations/Sources/Home/HotPlaceDashboard/HomeHotPlaceDashboardBuilder.swift, client/Targets/Presentation/Home/Implementations/Sources/Home/HotPlaceDashboard/HomeHotPlaceDashboardInteractor.swift, client/Targets/Presentation/Home/Implementations/Sources/Home/HotPlaceDashboard/HomeHotPlaceDashboardRouter.swift, client/Targets/Presentation/Home/Implementations/Sources/Home/HotPlaceDashboard/HomeHotPlaceDashboardViewController.swift, client/Targets/Presentation/Home/Implementations/Sources/Home/RecommendDashboard/HomeRecommendDashboardBuilder.swift, client/Targets/Presentation/Home/Implementations/Sources/Home/RecommendDashboard/HomeRecommendDashboardInteractor.swift, client/Targets/Presentation/Home/Implementations/Sources/Home/RecommendDashboard/HomeRecommendDashboardRouter.swift, client/Targets/Presentation/Home/Implementations/Sources/Home/RecommendDashboard/HomeRecommendDashboardViewController.swift, client/Targets/Presentation/Home/Implementations/Sources/Home/Views/HomeEmptyView.swift, client/Targets/Presentation/Home/Implementations/Sources/Home/Views/HomeSeeAllView.swift, client/Targets/Presentation/Home/Implementations/Sources/Home/Views/HomeTitleView.swift
* #62 
* PR이 너무 커질 것 같아서 비어있는 케이스(정보가 없을 때)만 따로 해서 PR로 올립니다
* 추천 장소 section 추가
* 핫플레이스 section 추가
* 팔로잉 section 추가
* Home이 추천 장소, 핫플레이스, 팔로잉에 대한 리블렛을 가지고 있는 구조
* 즉 1개의 ViewController와 3개의 ViewController가 존재
=> Home UI 추가 (Empty Case)

client/Targets/App/Sources/AppRoot/AppRootInteractor.swift, client/Targets/App/Sources/AppRoot/AppRootRouter.swift, client/Targets/App/Sources/AppRoot/AppRootTabBarController.swift, client/Targets/Presentation/Story/Implementations/Sources/StoryEditor/StoryEditorInteractor.swift, client/Targets/Presentation/Story/Implementations/Sources/StoryEditor/StoryEditorViewController.swift
* #53 
* 스토리 생성 취소 시 Home Tab 이동 추가
* App Root 수정으로 conflict 방지를 위해 먼저 PR 날립니다
*
=> 스토리 생성 취소 시 Home tab 이동 추가

client/Targets/App/Sources/AppRoot/AppRootComponent.swift, client/Targets/App/Sources/AppRoot/AppRootInteractor.swift, client/Targets/App/Sources/AppRoot/AppRootRouter.swift, client/Targets/App/Sources/AppRoot/AppRootTabBarController.swift, client/Targets/Presentation/Story/Implementations/Sources/StoryCreator/StoryCreatorBuilder.swift, client/Targets/Presentation/Story/Implementations/Sources/StoryCreator/StoryCreatorInteractor.swift, client/Targets/Presentation/Story/Implementations/Sources/StoryCreator/StoryCreatorRouter.swift, client/Targets/Presentation/Story/Implementations/Sources/StoryCreator/StoryCreatorViewController.swift, client/Targets/Presentation/Story/Implementations/Sources/StoryEditor/StoryEditorInteractor.swift, client/Targets/Presentation/Story/Implementations/Sources/StoryEditor/StoryEditorViewController.swift
* #53 
* 스토리 생성 리블렛 추가
* TabBar에 연결한 StoryEditor를 StoryCreator로 교체하고 StoryCreator가 Editor를 attach하도록 교체
* 스토리 생성 취소 시 이전 사용한 탭으로 이동하도록 교체
* 직전 PR이 거의 의미가 없었네요... 죄송합니다. 
* Editor view 구현 전에 끊어서 PR 날립니다.
=> StoryCreator 추가

server/src/auth/auth.service.ts, server/src/entities/story.entity.ts, server/src/entities/storyImage.entity.ts, server/src/exception/cuntom.exception/token.invalid.exception.ts, server/src/search/search.repository.ts, server/src/story/story.service.ts
* close #124 
- Invalid 토큰을 이용한 로그인, 회원가입 시도 시 498 Status code와 메세지를 리턴합니다.
- Story Entity 연관관계 수정
=> custom 에러 추가(Invalid 토큰 검사), Entity 연관 관계 수정

client/Targets/Presentation/Story/Implementations/Sources/StoryEditor/Components/AttributeField.swift, client/Targets/Presentation/Story/Implementations/Sources/StoryEditor/Components/AttributeTableViewCell.swift, client/Targets/Presentation/Story/Implementations/Sources/StoryEditor/Components/DescriptionField.swift, client/Targets/Presentation/Story/Implementations/Sources/StoryEditor/Components/ImageField.swift, client/Targets/Presentation/Story/Implementations/Sources/StoryEditor/Components/ImageSelector.swift, client/Targets/Presentation/Story/Implementations/Sources/StoryEditor/Components/TextFieldWithPadding.swift, client/Targets/Presentation/Story/Implementations/Sources/StoryEditor/Components/TitleField.swift, client/Targets/Presentation/Story/Implementations/Sources/StoryEditor/StoryEditorViewController.swift
* #53 
* 스토리 에디터에 필요한 기본 view를 추가했습니다.
* (수정) `cornerRadius`를 `DesignKit`의 `Constants`를 사용하도록 변경했습니다
* (수정) `TableViewCell`의 `ContetConfiguration`을 custom cell로 변경했습니다
* (수정)`UIPickerView`와 `UIDatePicker`를 `AttributeTableViewCell` 내부의 `valueLabel`의 `inputView`로 추가했습니다.
* 위치 정보는 추가로 작업이 필요합니다.
=> Story Editor View 추가

client/Targets/Core/CoreKit/Sources/CoreUtil/Result+Scheduler.swift, client/Targets/Core/Network/NetworkAPIKit/Sources/Network.swift, client/Targets/Core/Network/NetworkAPIKit/Sources/NetworkProvider.swift, client/Targets/Data/Repositories/Sources/AuthRepository.swift, client/Targets/Domain/Interfaces/Sources/Repository/AuthRepositoryInterface.swift, client/Targets/Domain/Interfaces/Sources/UseCase/AuthUseCaseInterface.swift, client/Targets/Domain/UseCases/Sources/AuthUseCase.swift, client/Targets/Presentation/Auth/Implementations/Sources/SignIn/SignInInteractor.swift, client/Targets/Presentation/Auth/Implementations/Sources/SignUp/SignUpInteractor.swift
* close #151 
* **후술할 방법보다 괜찮은 방법 있으면 꼭 말씀해주세요**
* 전에 얘기가 나왔던 Combine 덜어내기 했습니다.
* 데이터 스트림이 필요한 경우에는 Combine이 필요해서 두었고 1회 호출만 필요한 단순한 요청은 async/await 으로 변경했습니다.
* Task로 감싸서 실행을 하다 보니 메인 스레드 이슈가 있어서 Result 타입에 코드를 추가했습니다 (CoreKit을 import해야 사용 가능)
* onSuccess(+onFailure)를 호출할 때 Scheduler 그리고 참조를 할 객체를 넘길 수 있습니다.
* 참조는 약한 참조로 진행하며 객체를 가져올 수 없을 때는 호출되지 않습니다.
```swift
// 적용하기 전
Task { [weak self] in
guard let self else { return }
let result = await dependency.authUseCase
.requestSignUp(userName: userNameSubject.value)
switch result {
case .success(let value):
DispatchQueue.main.async { [weak self] in
self?.listener?.signUpDidComplete()
}
case .failure(let error):
print(error.localizedDescription)
}
// 적용한 후
Task { [weak self] in
guard let self else { return }
await dependency.authUseCase …
```
=> Network 요청 변경, Result Sugar 추가

client/Targets/Core/CoreKit/Sources/RIBsUtil/ViewControllable+Routing.swift
* close #149 
* 구두로 얘기했던 방식으로 해결했습니다.
* Dismiss/Pop되기 전에 endEditing 호출
* ViewController Dismiss/Pop 전에 EndEdit 추가
=> RIBs Keyboard Memory Leak 해결

client/Targets/Core/Network/NetworkAPIAuth/Sources/URLProtocols/AuthURLProtocol.swift, client/Targets/Data/Network/Sources/Auth/SignInResponseDTO.swift, client/Targets/Data/Network/Sources/Auth/SignUpResponseDTO.swift, client/Targets/Data/Repositories/Sources/NaverLoginRepository.swift, client/Targets/Presentation/Auth/Implementations/Sources/SignIn/SignInInteractor.swift
* close #89 
* 구두로 얘기했던 로그인/회원가입 API 연결 추가했습니다.
* 네이버 로그인 요청이 변경되었습니다.
* 기존 - Instance에 토큰이 있으면 해당 토큰을 재사용하였음
* 현재 - 반드시 요청을 하도록 변경하였음 (refreshToken을 받는 항목도 추가함)
* 로그인/회원가입 Response 변경
* 로그인/회원가입 분기 처리 추가 (토큰 여부에 따라)
* Naver 로그인 Token 요청 방식 변경
* AppRootComponent에 있는 Network Configuration을 수정하면 됩니다.
```swift
// 기존
override init(dependency: AppRootDependency) {
let naverLoginRepository: NaverLoginRepositoryInterface = {
let repository = NaverLoginRepository()
repository.setup()
return repository
}()
self.naverLoginRepository = naverLoginRepository
let network: Network = {
//            let configuration = URLSessionConfiguration.default
let configuration = URLSessionConfiguration.ephemeral
configuration.protocolClasses = [AuthURLProtocol.self]
let provider = NetworkProvider(session: …
```
=> 로그인/회원가입 API 연결

client/Targets/Data/Network/Project.swift, client/Targets/Data/Network/Tests/Sources/dummy.swift, client/Targets/Data/Repositories/Project.swift, client/Targets/Data/Repositories/Tests/Sources/dummy.swift, client/Targets/Data/Storages/Project.swift, client/Targets/Data/Storages/Tests/Sources/dummy.swift, client/Targets/Domain/UseCases/Project.swift, client/Targets/Domain/UseCases/Tests/Sources/dummy.swift, client/Targets/Presentation/Auth/Implementations/Project.swift, client/Targets/Presentation/Auth/Implementations/Tests/Sources/dummy.swift, client/Targets/Presentation/Home/Implementations/Project.swift, client/Targets/Presentation/Home/Implementations/Tests/Sources/dummy.swift, client/Targets/Presentation/Search/Implementations/Project.swift, client/Targets/Presentation/Search/Implementations/Tests/Sources/dummy.swift, client/Targets/Presentation/Story/Implementations/Project.swift, client/Targets/Presentation/Story/Implementations/Tests/Sources/dummy.swift, client/Tuist/ProjectDescriptionHelpers/Project+Templates.swift, client/Tuist/Stencils/Project-implementations.stencil, client/Tuist/Templates/feature/feature.swift
* close #166 
* 하단에 작성한 곳 Test 가능하도록 하였습니다.
* Presentation 모듈에는 Implementations 에 테스트 가능하도록 설정
* Data -> DataNetwork, DataRepositories
* Domain -> DomainUseCase
* Project Test Target 추가
* Tests 더미 데이터 추가
* tuist generate 후 각 모듈의 Tests 폴더에서 UnitTest를 추가해서 실행하면 됩니다.
* 추후 테스트 타겟을 추가하려면 Project에 .tests 추가 및 Tests폴더와 더미 데이터를 추가하면 됩니다.
=> Test Target 추가

client/Targets/App/Sources/AppRoot/AppRootBuilder.swift, client/Targets/App/Sources/AppRoot/AppRootComponent.swift, client/Targets/App/Sources/AppRoot/AppRootInteractor.swift, client/Targets/Core/CoreKit/Sources/SecretUtil/SecretManager.swift, client/Targets/Core/Network/NetworkAPIKit/Sources/NetworkHeader.swift, client/Targets/Data/Network/Auth/Sources/AuthAPI.swift, client/Targets/Data/Network/Base/Sources/NetworkHeader+Authorized.swift, client/Targets/Data/Network/Base/Sources/dummy.swift, client/Targets/Domain/Interfaces/Sources/UseCase/AuthUseCaseInterface.swift, client/Targets/Domain/UseCases/Sources/AuthUseCase.swift
* close #182 
* 추후 API 에서 Header를 설정할 때 BaseAPI를 import 하고 .authorized 를 사용하시면 자동으로 인증된 헤더를 사용하게 됩니다.
* **🚨현재 Mock으로 로그인 요청을 하고 있어서 로그인 요청하면 Mock Access Token이 저장되니까 주의해주세요!**
* SecretManager 추가
* Authorized Header 추가
* Root에 로그인 여부 처리 추가
* 처음에 앱을 실행하면 로그인 되지 않은 상태로 시작
* 로그인 후 앱을 종료하면 다음부터 로그인된 상태로 시작
* [SecretManager 레퍼런스](https://github.com/Nexters/phochak-iOS/blob/develop/Targets/Core/Sources/AuthManager.swift)
=> AccessToken Setup 추가

server/src/auth/auth.service.ts, server/src/entities/user.entity.ts, server/src/exception/custom.exception/badge.notValid.exception.ts, server/src/story/story.service.ts, server/src/user/user.controller.ts, server/src/user/user.service.ts
* close #190 
- 유저가 대표 badge를 설정할 수 있도록 구현했습니다.
- user/badge URI로 put 요청을 보내 실행시킬 수 있습니다
- 필요한 Body 데이터는 userId, BadgeName입니다.
- 유저가 가지고 있지 않은 BadgeName으로 설정하려 하는 경우, InvalidBadgeException이 발생합니다.
=> 대표 뱃지 설정 기능 구현

client/Targets/Presentation/Story/Implementations/Sources/StoryCreator/StoryCreatorBuilder.swift, client/Targets/Presentation/Story/Implementations/Sources/StoryCreator/StoryCreatorInteractor.swift, client/Targets/Presentation/Story/Implementations/Sources/StoryCreator/StoryCreatorRouter.swift, client/Targets/Presentation/Story/Implementations/Sources/StoryDetail/Components/SimpleUserProfileView.swift, client/Targets/Presentation/Story/Implementations/Sources/StoryDetail/Components/StoryHeaderView.swift, client/Targets/Presentation/Story/Implementations/Sources/StoryDetail/Components/StoryLikesCommentsView.swift, client/Targets/Presentation/Story/Implementations/Sources/StoryDetail/StoryDetailBuilder.swift, client/Targets/Presentation/Story/Implementations/Sources/StoryDetail/StoryDetailInteractor.swift, client/Targets/Presentation/Story/Implementations/Sources/StoryDetail/StoryDetailRouter.swift, client/Targets/Presentation/Story/Implementations/Sources/StoryDetail/StoryDetailViewController.swift, client/Targets/Presentation/Story/Implementations/Sources/StoryEditor/StoryEditorInteractor.swift, client/Targets/Presentation/Story/Implementations/Sources/StoryEditor/StoryEditorViewController.swift
* #239
* 스토리 생성 후 상세페이지로 이동하도록 router 로직 구현
* `viewController.pushViewController`, `viewController.popViewController` 코드에 버그가 있을 수도 있습니다.
* 지난번 `SignIn`과 마찬가지로 `popViewController`시에 memory leak error가 발생해서 `NavigationControllable`을 사용했습니다.
=> 스토리 생성 후 상세페이지 이동

client/Targets/Presentation/BasePresentation/Sources/Demo/DemoRootBuilder.swift, client/Targets/Presentation/BasePresentation/Sources/Demo/DemoRootInteractor.swift, client/Targets/Presentation/BasePresentation/Sources/Demo/DemoRootRouter.swift, client/Targets/Presentation/BasePresentation/Sources/Demo/DemoRootViewController.swift, client/Targets/Presentation/Home/Demo/Project.swift, client/Targets/Presentation/Home/Demo/Sources/AppDelegate.swift, client/Targets/Presentation/My/Demo/Project.swift, client/Targets/Presentation/My/Demo/Sources/AppDelegate.swift, client/Targets/Presentation/Search/Demo/Project.swift, client/Targets/Presentation/Story/Demo/Project.swift, client/Tuist/ProjectDescriptionHelpers/Project+Templates.swift, client/Tuist/Stencils/AppDelegate.stencil, client/Tuist/Stencils/Project-demo.stencil
* close #253 
* 기존 데모앱은 단순히 ViewController의 UI 로직만을 작업했습니다.
* 비즈니스 로직까지 작업할 수 있도록 Demo Root 리블렛을 추가했습니다.
* Demo Root 리블렛 추가
* Demo 템플릿 수정
* Demo 의존성 변경
* Home/MyPage Demo 설정
* 기존에 데모앱을 생성하는 방식대로 생성합니다.
* `tuist generate --path Targets/Presentation/My/Demo` 
* 앱 델리게이트 값을 설정합니다.
```swift
import UIKit
import MyInterfaces // 해당 모듈의 인터페이스
import MyImplementations // 해당 모듈의 구현체
import ModernRIBs
import CoreKit
import NetworkAPIKit
import BasePresentation
import DomainInterfaces
import DomainUseCases
import DataRepositories
@main
class AppDelegate: UIResponder, UIApplicationDelegate {
var window: UIWindow?
private var launchRouter: DemoRootRouter?
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
let …
```
=> Demo 앱 Sugar 추가

client/Targets/Core/CoreKit/Sources/TaskUtil/AnyCancellableTask.swift, client/Targets/Core/CoreKit/Sources/TaskUtil/CancelBag.swift
* close #257 
* Task (async/await)을 취소하기 위해 추가했습니다.
* CancelBag 추가
1. CoreKit import
2. CancelBag() 생성
3. Task {}.store(in: bag)
```swift
import CoreKit
private let cancelBag = CancelBag()
func fetchHotPlace() {
Task {
await dependency.hotPlaceUseCase.fetchHotPlace()
.onSuccess(on: .main, with: self) { this, stories in
this.performAfterFetchingHotPlace(stories: stories)
}
.onFailure { error in
Log.make(message: error.localizedDescription, log: .interactor)
}
}.store(in: cancelBag)
}
```
* [참고](https://minsone.github.io/swift-concurrency-AnyCancelTaskBag)
=> TaskCancelBag 추가

client/Targets/Core/CoreKit/Sources/Alert/ViewControllable+Alert.swift, client/Targets/Core/FoundationKit/Sources/Alert/AlertPresentable.swift, client/Targets/Core/FoundationKit/Sources/Alert/AlertType.swift, client/Targets/Core/FoundationKit/Sources/Alert/SignOutService+Alert.swift, client/Targets/Core/FoundationKit/Sources/User/SignOutService.swift, client/Targets/Core/Network/NetworkAPIKit/Sources/NetworkErrorCode.swift, client/Targets/Core/Network/NetworkAPIKit/Sources/NetworkProvider.swift, client/Targets/Presentation/My/Implementations/Sources/Setting/SettingInteractor.swift
* close #212 
* Alert Sugar 코드 추가
* Invalid Token일 경우 로그아웃 기능 추가
* NetworkProvider에 있는 상태 코드를 498로 변경하면 됩니다.
```swift
private func interceptResponseIfNeeded(_ response: URLResponse) {
guard let httpResponse = response as? HTTPURLResponse,
let errorCode = NetworkErrorCode(rawValue: httpResponse.statusCode) // 여기에 상태코드 대신 498로 변경
else {
return
}
switch errorCode {
case .invalidToken:
SignoutService.shared.signOut(type: .invalidToken)
default:
return
}
}
```
* FoundationKit에 Alert에 대한 정의가 있습니다.
* ViewControllable도 바로 동작할 수 있도록 만들어 놔서 Interactor에서 바로 사용할 수 있습니다.
```swift
// SettingInteractor.swift
func didTapResign() {
router?.viewControllable.present(type: .resign, okAction: {
print("탈퇴해주세요")
})
}
```
https://github.com/boostcampwm2023/iOS04-HeatPick/assets/74225754/d331c549-dad8-42e5-8238-6f …
=> Invalid Token 로그아웃 추가, Alert Sugar 추가

client/Targets/Presentation/Story/Implementations/Sources/StoryEditor/Components/ImageSelector.swift
* #340 
* PHPicker에서 사진만 보이도록 filter 적용
* Live Photo를 선택할 수 있도록 수정
* 사진 추가/삭제 버튼 크기 및 위치 수정
##🎇 스크린샷
=> ImageSelector가 live photo를 지원하도록 수정

client/Targets/App/Sources/AppRoot/AppRootRouter.swift, client/Targets/Data/Network/Search/Sources/DTO/SearchRecommendResponseDTO.swift, client/Targets/Data/Repositories/Sources/SearchRepository.swift, client/Targets/Presentation/Search/Implementations/Sources/Search/SearchBuilder.swift, client/Targets/Presentation/Search/Implementations/Sources/Search/SearchInteractor.swift, client/Targets/Presentation/Search/Implementations/Sources/Search/SearchResult/SearchAfterDashboard/SearchAfterDashboardInteractor.swift, client/Targets/Presentation/Search/Implementations/Sources/Search/SearchResult/SearchAfterDashboard/SearchAfterStoryDashboard/SearchAfterStoryDashboardInteractor.swift, client/Targets/Presentation/Search/Implementations/Sources/Search/SearchResult/SearchAfterDashboard/SearchAfterStoryDashboard/SearchAfterStoryDashboardViewController.swift, client/Targets/Presentation/Search/Implementations/Sources/Search/SearchResult/SearchAfterDashboard/SearchAfterStoryDashboard/Views/SearchAfterStoryView.swift, client/Targets/Presentation/Search/Implementations/Sources/Search/SearchResult/SearchAfterDashboard/SearchAfterUserDashboard/SearchAfterUserDashboardViewController.swift, client/Targets/Presentation/Search/Implementations/Sources/Search/SearchResult/SearchBeforeDashboard/SearchBeforeCategoryDashboard/Views/SearchBeforeCategoryView.swift, client/Targets/Presentation/Search/Implementations/Sources/Search/SearchResult/SearchBeforeDashboard/SearchBeforeRecentSearchesDashboard/SearchBeforeRecentSearchesDashboardInteractor.swift, client/Targets/Presentation/Search/Implementations/Sources/Search/SearchResult/SearchBeforeDashboard/SearchBeforeRecentSearchesDashboard/Views/SearchBeforeRecentSearchesEmptyView.swift, client/Targets/Presentation/Search/Implementations/Sources/Search/SearchResult/SearchBeforeDashboard/SearchBeforeRecentSearchesDashboard/Views/SearchBeforeRecentSearchesView.swift, client/Targets/Presentation/Search/Implementations/Sources/Search/SearchResult/SearchResultInteractor.swift, client/Targets/Presentation/Search/Implementations/Sources/Search/SearchResult/SearchResultRouter.swift, client/Targets/Presentation/Search/Implementations/Sources/Search/SearchRouter.swift, client/Targets/Presentation/Search/Interfaces/Sources/SearchInterface.swift
- #279 
- 어제 부검한 UI 수정
- 스토리 클릭시 스토리 상세로 이동
- SearchInterface 생성 및 적용
* PR를 볼 때 도움이 되는 항목 추가
https://github.com/boostcampwm2023/iOS04-HeatPick/assets/71696675/d383db85-fda6-4465-adfe-d886613f2eda
시뮬레이터 키보드 에러
```
[UIKeyboardTaskQueue lockWhenReadyForMainThread] timeout waiting for task on queue
```
=> 검색 스토리상세 구현

client/Targets/App/Sources/AppRoot/AppRootComponent.swift, client/Targets/Core/Network/NetworkAPIKit/Sources/NetworkErrorCode.swift, client/Targets/Core/Network/NetworkAPIKit/Sources/NetworkProvider.swift
* close #428 
* 로그에 Unauthorized가 떠서 추가했습니다.
* 자동으로 refresh 하도록 추가하면 좋을 것 같은데 아직 중요한 기능이 아니라 나중으로 미루겠습니다.
* 401 에러일 때 로그아웃하도록 추가
* Network에 로그아웃 서비스 의존성 추가
* URLProtocol에 상태코드를 200에서 401로 변경하면 테스트 가능
https://github.com/boostcampwm2023/iOS04-HeatPick/assets/74225754/f25e0ea0-1c88-4939-8336-4847dd129bee
=> 인증 토큰 만료 로직 추가

server/src/comment/comment.service.ts, server/src/entities/story.entity.ts, server/src/story/story.controller.ts, server/src/story/story.service.ts, server/src/util/story.entity.to.obj.ts
* close #422 
- 현재 유저의 팔로우들의 게시물을 리턴합니다.
- sortOption을 파라미터로 줄 수 있으며, default 값은 0입니다.
- 0인 경우 최신순, 1인 경우 좋아요 순, 2인 경우 댓글 순으로 스토리를 리턴합니다.
- offset과 limit을 통해 원하는 양 만큼 스토리를 리턴받을 수 있으며 파라미터를 넘겨주지 않은 경우 offset은 0, limit은 5로 배정됩니다.
=> 팔로우 기반 게시물 리턴 기능 구현

client/Targets/Core/CoreKit/Sources/CoreUtil/String+.swift, client/Targets/Data/Network/Home/Sources/DTO/RecommendLocationResponseDTO.swift, client/Targets/Data/Network/Home/Sources/DTO/RecommendResponseDTO.swift, client/Targets/Data/Network/My/Sources/DTO/MyProfileResponseDTO.swift, client/Targets/Data/Network/Search/Sources/DTO/SearchStroyDTO.swift, client/Targets/Data/Network/Story/Sources/DTO/StoryDetailResponseDTO.swift, client/Targets/Data/Network/Story/Sources/DTO/StoryResponseDTO.swift
* close #438 
* Label에 \n 그대로 표현되고 있어서 추가했습니다.
* 스토리 상세 내용에만 필요할 것 같아서 ResponseDTO에 story content가 있으면 변경하도록 추가했습니다.
* Story Content에 개행 replace 추가
|AS-IS|TO-BE|
|--|--|
|![IMG_5648](https://github.com/boostcampwm2023/iOS04-HeatPick/assets/74225754/657e55ef-ac38-4c3f-80c1-bccaabbb24e0)|![IMG_5650](https://github.com/boostcampwm2023/iOS04-HeatPick/assets/74225754/6ad68109-e10d-4913-a032-88e7247b70e0)|
|![IMG_5649](https://github.com/boostcampwm2023/iOS04-HeatPick/assets/74225754/653ba018-6c8e-4c9b-b1df-cd0805a03b91)|![IMG_5651](https://github.com/boostcampwm2023/iOS04-HeatPick/assets/74225754/3c9154dd-4d12-4238-96b1-05eae81c611b)|
=> Label 개행 오류 수정

client/Targets/App/Sources/AppRoot/AppRootComponent.swift, client/Targets/App/Sources/AppRoot/AppRootInteractor.swift, client/Targets/App/Sources/AppRoot/AppRootRouter.swift, client/Targets/App/Sources/AppRoot/AppRootTabBarController.swift, client/Targets/Data/Repositories/Sources/FollowingRepository.swift, client/Targets/Domain/Entities/Sources/Home/HomeFollowingSortOption.swift, client/Targets/Domain/Interfaces/Sources/Repository/FollowingRepositoryInterface.swift, client/Targets/Domain/Interfaces/Sources/UseCase/Following/FollowingUseCaseInterface.swift, client/Targets/Domain/UseCases/Sources/FollowingUseCase.swift, client/Targets/Presentation/Following/Implementations/Sources/FollowingHome/FollowingHomeBuilder.swift, client/Targets/Presentation/Following/Implementations/Sources/FollowingHome/FollowingHomeInteractor.swift, client/Targets/Presentation/Following/Implementations/Sources/FollowingHome/FollowingHomeRouter.swift, client/Targets/Presentation/Following/Implementations/Sources/FollowingHome/FollowingHomeViewController.swift, client/Targets/Presentation/Following/Implementations/Sources/FollowingList/FollowingListBuilder.swift, client/Targets/Presentation/Following/Implementations/Sources/FollowingList/FollowingListInteractor.swift, client/Targets/Presentation/Following/Implementations/Sources/FollowingList/FollowingListRouter.swift, client/Targets/Presentation/Following/Implementations/Sources/FollowingList/FollowingListViewController.swift, client/Targets/Presentation/Following/Implementations/Sources/FollowingList/Views/FollowingDropDownView.swift, client/Targets/Presentation/Following/Implementations/Sources/FollowingList/Views/FollowingListCell.swift, client/Targets/Presentation/Following/Implementations/Sources/FollowingList/Views/FollowingListCommnetView.swift, client/Targets/Presentation/Following/Implementations/Sources/FollowingList/Views/FollowingListProfileView.swift, client/Targets/Presentation/Following/Implementations/Sources/FollowingList/Views/FollowingTitleView.swift, client/Targets/Presentation/Home/Implementations/Sources/Home/HomeBuilder.swift, client/Targets/Presentation/Home/Implementations/Sources/Home/HomeInteractor.swift, client/Targets/Presentation/Home/Implementations/Sources/Home/HomeRouterComponent.swift, client/Targets/Presentation/Home/Interfaces/Sources/HomeInterface.swift, client/Targets/Presentation/Search/Implementations/Sources/Search/SearchBuilder.swift, client/Targets/Presentation/Search/Implementations/Sources/Search/SearchRouter.swift
* close #448 
* 최근 활동 쪽 작업이 아직 진행되지 않아 일단 팔로잉 화면 하나만 들어온다고 가정하고 UI 그려놨습니다.
* 추후 작업이 진행되면 StackView+ScrollView 이용해서 붙이겠습니다!
* 홈화면에서 팔로잉 모두보기 버튼을 누를 시 팔로잉 탭을 선택하도록 추가했습니다.
* (참고) 최신순/좋아요순/댓글순 정렬 호출 하는데 값이 동일해서 화면 리로드가 되지 않습니다
* 팔로잉 UI 추가
* 팔로잉 서비스 추가
* 팔로잉 모두보기 라우팅 추가
https://github.com/boostcampwm2023/iOS04-HeatPick/assets/74225754/574f0446-f6c1-4cb9-b940-a13de26e59d1
=> 팔로잉 서비스 추가

client/Targets/Data/Network/Story/Sources/DTO/CommentReadResponseDTO.swift, client/Targets/Presentation/Story/Implementations/Sources/StoryDetail/Components/SimpleUserProfileView.swift, client/Targets/Presentation/Story/Implementations/Sources/StoryDetail/StoryDetailInteractor.swift
* #417 
* 팔로우/언팔로우 버튼 디자인 수정
* 팔로우/언팔로우 버튼 클릭 시 네트워크 작업 완료 전까지 버튼을 비활성화
* Response line break 수정
=> 팔로우/언팔로우 버튼 수정

client/Targets/Presentation/My/Implementations/Sources/MyPage/UserDashboard/MyPageUserDashboardInteractor.swift, client/Targets/Presentation/Search/Implementations/Sources/Search/SearchViewController.swift, client/Targets/Presentation/Search/Implementations/Sources/Search/Views/SearchMapStoryView.swift
* close #457 
* 지도에서 스토리 상세 탭 되는 영역이 바깥 영역만 되어서 수정했습니다.
* +마이페이지에 경험치 표현하는 방식 변경했습니다 (작은거라 포함했슴다)
* 지도 스토리 상세 터치 영역 수정
* 마이페이지 경험치 로직 변경
=> 지도 스토리 선택 범위 수정

client/Targets/Domain/Entities/Sources/User/UserStatus.swift
* #468 
* 서버에서는 non-following이 1번, following이 2번으로 되어있고, client에서는 반대로 되어있는 문제
* UserStatus reorder
=> UserStatus 순서 수정

client/Targets/Core/CoreKit/Sources/CombineUtil/ControlPubliser.swift, client/Targets/Core/CoreKit/Sources/CombineUtil/Publisher+.swift, client/Targets/Core/CoreKit/Sources/CombineUtil/UIButton+Combine.swift, client/Targets/Core/CoreKit/Sources/CombineUtil/UIControl+Combine.swift, client/Targets/Core/CoreKit/Sources/CombineUtil/UITextField+Combine.swift, client/Targets/Core/CoreKit/Sources/CombineUtil/UITextView+Combine.swift, client/Targets/Presentation/Auth/Implementations/Sources/SignIn/SignInViewController.swift
* close #474 
* 왜 필요한가?
* 현재 이벤트가 각각 분리되어있어 해당 ViewController에서의 Output을 보기 어려움
* 데이터 스트림을 통해 직관적으로 확인할 수 있어 가독성에 좋음
* UIKit Control Publisher 추가
* Combine Unretained 추가
* SignIn Combine 추가
* with 메소드는 객체를 약한 참조해서 가져옵니다.
* withOnly는 객체를 약한 참조해서 그 객체'만' 가져옵니다
* 샘플로 SignIn에 적용해뒀습니다.
```swift
func bind() {
naverLoginButton.tapPublisher
.withOnly(self)
.sink { $0.listener?.naverButtonDidTap() }
.store(in: &cancellables)
appleLoginButton.tapPublisher
.withOnly(self)
.sink { $0.listener?.appleButtonDidTap() }
.store(in: &cancellables)
}
```
* [참조](https://github.com/CombineCommunity/CombineCocoa)
=> Combine Cocoa 추가

client/Targets/Presentation/Story/Implementations/Sources/StoryDetail/Components/ImageCountButton.swift, client/Targets/Presentation/Story/Implementations/Sources/StoryDetail/Components/StoryHeaderView.swift
* #507
* likebutton 이미지 눌렸을 때 채우도록 변경
*
=> likebutton 이미지 눌렸을 때 채우도록 변경

client/Targets/Domain/Interfaces/Sources/UseCase/Search/SearchCurrentLocationStoryList/SearchCurrentLocationStoryListUseCaseInterface.swift, client/Targets/Domain/UseCases/Sources/SearchUseCase.swift, client/Targets/Presentation/My/Implementations/Sources/MyPage/MyPageInteractor.swift, client/Targets/Presentation/Search/Implementations/Sources/Search/SearchCurrentLocationStoryList/SearchCurrentLocationStoryListBuilder.swift, client/Targets/Presentation/Search/Implementations/Sources/Search/SearchCurrentLocationStoryList/SearchCurrentLocationStoryListInteractor.swift, client/Targets/Presentation/Search/Implementations/Sources/Search/SearchCurrentLocationStoryList/SearchCurrentLocationStoryListViewController.swift, client/Targets/Presentation/Search/Implementations/Sources/Search/SearchCurrentLocationStoryList/Views/SearchCurrentLocationStoryEmptyView.swift, client/Targets/Presentation/Search/Implementations/Sources/Search/SearchCurrentLocationStoryList/Views/SearchCurrentLocationStoryListCell.swift, client/Targets/Presentation/Search/Implementations/Sources/Search/SearchInteractor.swift, client/Targets/Presentation/Search/Implementations/Sources/Search/SearchRouter.swift
* close #542 
* 기존 UI랑 변경된 사항이 있습니다.
* 기존 UI는 스토리 작성자를 나타내는데 Response에 유저 정보가 없어서 그냥 없애고 스토리 상세 내용 1줄 나오도록 변경했습니다.
* 현재 위치 정보가 모달이라서 push하기 애매해서 모달 창 내리고 스토리 상세 push하도록 하였습니다.
* 현재 위치 스토리 리스트 추가
* 현재 위치 스토리 리스트 라우팅 (스토리 상세) 추가
https://github.com/boostcampwm2023/iOS04-HeatPick/assets/74225754/2c259461-f2eb-4c53-a70b-c7925b3bd957
=> 현재 위치 스토리 리스트 추가

server/src/exception/custom.exception/fcm-token-save-failed.exception.ts, server/src/notification/dto/save-token-request.dto.ts, server/src/notification/notification.controller.ts, server/src/notification/notification.module.ts, server/src/notification/notification.service.ts
* #562 
* fcm 토큰을 저장하는 api 생성
* POST /notification/save-fcm-token
* Body 요구사항 => { fcmToken: string }
=> fcm 토큰을 저장하는 api 생성

client/Targets/Presentation/Story/Implementations/Sources/StoryEditor/Components/ImageField.swift, client/Targets/Presentation/Story/Implementations/Sources/StoryEditor/StoryEditorInteractor.swift, client/Targets/Presentation/Story/Implementations/Sources/StoryEditor/StoryEditorViewController.swift
* #595 
* 스토리 생성 시 이미지를 추가해야 버튼이 활성화 되도록 했습니다.
=> 스토리 생성 시 이미지 필요하도록 추가

server/src/story/story.service.ts
스토리 추천 기능에서 null 데이터 제거 로직을 장소 기반 추천 / 핫플레이스에도 적용
=> 스토리 추천 기능에서 null 데이터 제거

client/Targets/Core/CoreKit/Sources/CoreUtil/String+.swift, client/Targets/Data/Network/Search/Sources/DTO/NaverSearchLocalRequestDTO.swift, client/Targets/Data/Network/Search/Sources/DTO/NaverSearchLocalResponseDTO.swift, client/Targets/Domain/Entities/Sources/Search/SearchLocal.swift, client/Targets/Presentation/Search/Implementations/Sources/Search/SearchInteractor.swift, client/Targets/Presentation/Search/Implementations/Sources/Search/SearchResult/SearchAfterDashboard/SearchAfterDashboardInteractor.swift, client/Targets/Presentation/Search/Implementations/Sources/Search/SearchResult/SearchAfterDashboard/SearchAfterLocalDashboard/SearchAfterLocalDashboardInteractor.swift, client/Targets/Presentation/Search/Implementations/Sources/Search/SearchResult/SearchAfterDashboard/SearchAfterLocalDashboard/SearchAfterLocalDashboardViewController.swift, client/Targets/Presentation/Search/Implementations/Sources/Search/SearchResult/SearchAfterDashboard/SearchAfterLocalDashboard/Views/SearchAfterLocalView.swift, client/Targets/Presentation/Search/Implementations/Sources/Search/SearchResult/SearchResultInteractor.swift, client/Targets/Presentation/Search/Implementations/Sources/Search/SearchViewController.swift
* close #536 
* 네이버 검색 API 탭 되었을 때 라우팅 동작 추가했습니다.
* 따로 네이버 검색 API에 가이드라인이 없어서 일단 받은 String 잘라서 사용하는 것으로 했습니다.
* 가이드라인이 없어서 불안하긴 합니다 ㅋㅋ.. 일단 잘 동작해서 넣어두겠습니다.
* 위치 정보 없을 때 default 위치로 네이버 1784 로 찍어놨습니다.
* 네이버 검색 후 지도 라우팅 추가
* HTML 태그 제거
https://github.com/boostcampwm2023/iOS04-HeatPick/assets/74225754/9b632d3e-5b6e-4241-a03d-3440158c7557
=> 지도 검색 라우팅 추가

client/Targets/Core/FoundationKit/Sources/UserDefaults/UserDefaults+.swift, client/Targets/Core/FoundationKit/Sources/UserDefaults/UserDefaults+Key.swift, client/Targets/Data/Network/Search/Sources/DTO/SearchRecommendResponseDTO.swift, client/Targets/Data/Network/Search/Sources/DTO/SearchRequestDTO.swift, client/Targets/Data/Network/Search/Sources/DTO/SearchStroyDTO.swift, client/Targets/Data/Network/Search/Sources/DTO/SearchStroyResponseDTO.swift, client/Targets/Data/Network/Search/Sources/SearchAPI.swift, client/Targets/Data/Network/Search/Sources/URLProtocols/SearchURLProtocol.swift, client/Targets/Data/Repositories/Sources/SearchRepository.swift, client/Targets/Domain/Interfaces/Sources/Repository/Search/SearchSeeAllRepositoryInterface.swift, client/Targets/Domain/Interfaces/Sources/UseCase/Search/SearchSeeAll/SearchStorySeeAllUseCaseInterface.swift, client/Targets/Domain/Interfaces/Sources/UseCase/Search/SearchSeeAll/SearchUserSeeAllUseCaseInterface.swift, client/Targets/Domain/UseCases/Sources/SearchUseCase.swift, client/Targets/Presentation/BasePresentation/Sources/Story/StorySeeAll/StorySeeAllViewController.swift, client/Targets/Presentation/BasePresentation/Sources/User/Cells/UserSmallTableViewCell.swift, client/Targets/Presentation/BasePresentation/Sources/User/UserSeeAll/UserSeeAllPresentable.swift, client/Targets/Presentation/BasePresentation/Sources/User/UserSeeAll/UserSeeAllViewController.swift, client/Targets/Presentation/Search/Implementations/Sources/Search/SearchInteractor.swift, client/Targets/Presentation/Search/Implementations/Sources/Search/SearchResult/SearchAfterDashboard/SearchAfterDashboardViewController.swift, client/Targets/Presentation/Search/Implementations/Sources/Search/SearchResult/SearchAfterDashboard/SearchAfterLocalDashboard/SearchAfterLocalDashboardViewController.swift, client/Targets/Presentation/Search/Implementations/Sources/Search/SearchResult/SearchAfterDashboard/SearchAfterUserDashboard/SearchAfterUserDashboardViewController.swift, client/Targets/Presentation/Search/Implementations/Sources/Search/SearchResult/SearchAfterDashboard/SearchAfterUserDashboard/Views/SearchAfterUserView.swift, client/Targets/Presentation/Search/Implementations/Sources/Search/SearchResult/SearchResultViewController.swift, client/Targets/Presentation/Search/Implementations/Sources/Search/SearchRouter.swift, client/Targets/Presentation/Search/Implementations/Sources/Search/SearchViewController.swift, client/Targets/Presentation/Search/Implementations/Sources/Search/SeeAll/Story/SearchStorySeeAllInteractor.swift, client/Targets/Presentation/Search/Implementations/Sources/Search/SeeAll/User/SearchUserSeeAllInteractor.swift, client/Targets/Presentation/Search/Implementations/Sources/Search/Views/SearchMapSearchView.swift
* close #635 
* 검색 쪽 버그 작업 했습니다.
* 지도 홈 화면에서 검색 TextField가 TextField라서 실제 텍스트가 입력이 되는 버그가 있어 View로 변경했습니다.
* 재검색이 스크롤을 너무 많이 해야 한다는 얘기가 있어서 조금해도 등장할 수 있도록 수치를 변경했습니다.
* 검색 결과 모두 보기 기능 추가 (스토리, 유저)
* 스토리/유저 모두 보기 페이징 처리 추가
* 유저 모두 보기 UI 변경
* 기타 레이아웃 변경
* 지도 홈 화면 검색 TextField 대신 View로 대체
* 재검색 active 값 수정
https://github.com/boostcampwm2023/iOS04-HeatPick/assets/74225754/e44d424c-22d6-4801-a1d9-6222735de388
https://github.com/boostcampwm2023/iOS04-HeatPick/assets/74225754/5a2f126f-0c77-4599-ae0e-67c426d9986b
=> 검색 탭 버그 수정

client/Targets/Core/FoundationKit/Sources/UserDefaults/UserDefaults+Key.swift, client/Targets/Domain/Interfaces/Sources/UseCase/Search/SearchMap/SearchMapUseCaseInterface.swift, client/Targets/Domain/UseCases/Sources/SearchUseCase.swift, client/Targets/Presentation/Search/Implementations/Sources/Search/SearchInteractor.swift, client/Targets/Presentation/Search/Implementations/Sources/Search/SearchViewController.swift, client/Targets/Presentation/Search/Implementations/Sources/Search/Views/SearchStoryGuideView.swift
* close #669 
* 스토리 가이드 노출 여부에 따라 1회 노출됩니다 (UserDefaults 사용)
* 지도 화면에 스토리 생성 가이드 추가
https://github.com/boostcampwm2023/iOS04-HeatPick/assets/74225754/138915a4-381d-4247-8e47-ed3f95c4b970
=> 스토리 생성 가이드 추가

server/src/story/story.service.ts
* close #680 
- 스토리 생성 시 경험치 100 제공으로 변경
=> 스토리 생성 시 경험치 제공량 변경
